### ISSUE TITLE
Which version of ogre is used for meta-ros1-melodic?

### ISSUE THREAD

**Issue by ABTrac** [ros/meta-ros#1010]
Dear community,

I want  to add meta-ros to an existing yocto build for Nvidia Jetson-agx-xavier. I have added meta-ros as instructed in [https://github.com/ros/meta-ros/wiki/OpenEmbedded-Build-Instructions#add-meta-ros-to-an-existing-openembedded-project](https://github.com/ros/meta-ros/issues/url) and everything compiles successfully for the `ros-image-core`.

However, I noticed that the `meta-ros1-melodic` from the Dunfell branch uses **ogre version 1.12.9**. Is this the correct version for  `meta-ros1-melodic`?  

When I compared it with the version used for on an `Ubuntu 18.04` device which has `ros-melodic-desktop-full` installed using apt install, I found it uses **ogre version 1.9** .

`ogre` is needed for building  `rviz`, which is complaining when I try to compile it using `ogre 1.12.8`, so before I try version 1.9 I wanted to confirm if that is necessary . 

Can someone please confirm which ogre version should be used for the `meta-ros1-melodic`. Thank you very much for the help :)

**Comment by robwoolley** [comment]
The generated base.yaml file (meta-ros1-melodic/files/melodic/generated/rosdep/base.yaml) indicates that the various Linux distros used libogre-1.9 for melodic.  The newer version was likely chosen for meta-ros-common to support later ROS2 distros.
