### ISSUE TITLE
honister-humble build realtime-tools & hardware-interfaces failed

### ISSUE THREAD

**Issue by panxxhub** [ros/meta-ros#1016]
**Describe the bug**
EORROR: realtime-tools-2.2.0-3-r0 do_configure: ExecutionError('/**/build/tmp/work/cortexa72-cortexa53-xilinx-linux/realtime-tools/2.2.0-3-r0/temp/run.do_configure.3482850', 1, None, None)
ERROR: Logfile of failure stored in: /**/build/tmp/work/cortexa72-cortexa53-xilinx-linux/realtime-tools/2.2.0-3-r0/temp/log.do_configure.3482850
**To Reproduce**
OS: VERSION="20.04.4 LTS (Focal Fossa)"
petalinux: 2022.1(without update1)
ROS_OE_RELEASE_SERIES = "honister"
ROS_DISTRO = "humble"
IMAGE_INSTALL:append = " \
    ros-base \
    examples-rclcpp-minimal-action-client \
    realtime-tools \
"

**Expected behavior**
ERROR: Task (/**/project-spec/meta-ros/meta-ros2-humble/generated-recipes/realtime-tools/realtime-tools_2.2.0-3.bb:do_configure) failed with exit code '1'

**Comment by panxxhub** [comment]
possible fix:
add realtime-tools_%.bbappend

ROS_BUILD_DEPENDS += " \
    python3-numpy-native \
"

**Comment by robwoolley** [comment]
Honister is no longer supported, however this change was previously made to hardware-interfaces for kirkstone + humble.  Both realtime-tools and hardware-interfaces build.
