### ISSUE TITLE
honister-humble build control-msgs failed

### ISSUE THREAD

**Issue by panxxhub** [ros/meta-ros#1017]
**Describe the bug**
ERROR: control-msgs-3.0.0-1-r0 do_package: QA Issue: control-msgs: Files/directories were installed but not shipped in any package:

**To Reproduce**
OS: VERSION="20.04.4 LTS (Focal Fossa)"
petalinux: 2022.1(without update1)
ROS_OE_RELEASE_SERIES = "honister"
ROS_DISTRO = "humble"
IMAGE_INSTALL:append = " \
    ros-base \
    control-msgs \
"

**Expected behavior**

**Comment by vectorcrumb** [comment]
Were you able to resolve this issue? I'm also getting an error on control-msgs when trying to build a Petalinux image for the KR260 platform.

**Comment by grsandeep85** [comment]
Hi @vectorcrumb,

We have fixed some ros2-control packages build issues last week, we will push the changes asap.

**Comment by grsandeep85** [comment]
Hi @vectorcrumb,

Patches are pushed in repo  https://github.com/Xilinx/meta-ros/compare/b170fbcd5d85...bb62e31839b3

**Comment by vectorcrumb** [comment]
Thanks @grsandeep85 !
What is the reason behind using `inherit distutils3-base` and having to specify `python3-numpy-native` as a build dependency so often?

**Comment by ctgulzh** [comment]
What are the specific steps for cross-compiling ROS 2 message and function packages on the host using the petalinux tool? Can they be compiled as libraries or apps? (See https://xilinx-wiki.atlassian.net/wiki/spaces/A/pages/18842475/PetaLinux+Yocto+Tips#PetaLinuxYoctoTips-HowtoAddPre-builtLibrariesinPetaLinuxorYoctoProjects.) Or do I need to use the devtool tool for cross-compilation?
