### ISSUE TITLE
ROS2 humble printenv ROS_DISTRO gives output as 'Rolling'

### ISSUE THREAD

**Issue by suyash-narain** [ros/meta-ros#1024]
Hi @vmayoral 

I am trying to build a ros2 humble image using your fork https://github.com/vmayoral/meta-ros/tree/honister-humble and even though the image gets built, when I run `printenv ROS_DISTRO` I get output as `rolling` instead of `humble` which should not be the case. It seems even though am calling meta-ros2-humble, somewhere in some ros workspace recipe it is building rolling version of ROS2. 
Some suggestions here would be great. I am using an aarch64 platform using honister version of yocto

thanks

**Comment by grsandeep85** [comment]
Hi @suyash-narain ,

Apply attached patches, issue will be resolved.
[meta-ros.zip](https://github.com/ros/meta-ros/files/9412323/meta-ros.zip)

**Comment by vmayoral** [comment]
Thanks @grsandeep85 and @mhatle, patches are now pushed into the `honister-humble` branch. See https://github.com/ros/meta-ros/pull/1003.

We can close this ticket.
