### ISSUE TITLE
Two recipes for foonathan/memory

### ISSUE THREAD

**Issue by h1r4n** [ros/meta-ros#1025]
Why are there two recipes for foonathan-memory?

Recipe 1 - foonathan-memory-vendor  in generated recipes (eg meta-ros2-galactic/generated-recipes/foonathan-memory-vendor) - which builds foonathan-memory for fastrtps/fastdds

Recipe 2 - foonatahn-memory in meta-ros2/recipes-devtools which also builds foonathan-memeory

What is the reason for this?

Which one is used in the end?

**Comment by robwoolley** [comment]
The foonathan-memory-vendor is a meta-package whose purpose is to depend on the library provided by the OS.  In our case, the foonathan-memory is provided by meta-ros, but it is not a recipe generated by superflore.  This makes it a library provided by "Yocto/OE" and not by "ROS".  In the end both are used by foonathan-memory-vendor just provides CMake files and a package.xml.
