### ISSUE TITLE
allow to compile ROS packages on the target using the dev packages

### ISSUE THREAD

**Issue by bulwahn** [ros/meta-ros#103]
One use case might be to compile ROS packages on the target, e.g. for debugging purposes.

With a image with

IMAGE_INSTALL += "\
  packagegroup-core-ssh-openssh \
  util-linux \
  catkin-dev \
  message-generation-dev \
  gencpp-dev \
  genmsg-dev \
  genlisp-dev \
  genpy-dev \
  std-msgs-dev \
  message-runtime-dev \
  cpp-common-dev \
  roscpp-serialization-dev \
"

and downloading the example ros_chatter master and executing the following lines on the target (in this case, the qemu VM):

> scp user@192.168.7.1:/download-location/ros_chatter-master.zip .
> export CMAKE_PREFIX_PATH=/usr
> mkdir -p catkin_ws/src
> cd catkin_ws
> catkin_init_workspace src
> unzip ../ros_chatter-master.zip -d src
> catkin_make

It breaks down with:

> -- Using CATKIN_TEST_RESULTS_DIR: /home/root/catkin_ws/build/test_results
> -- catkin 0.5.64
> -- BUILD_SHARED_LIBS is on
> -- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> -- ~~  traversing 3 packages in topological order:
> -- ~~  - chatter_msgs
> -- ~~  - chatter_receiver
> -- ~~  - chatter_sender
> -- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> -- +++ processing catkin package: 'chatter_msgs'
> -- ==> add_subdirectory(ros_chatter-master/chatter_msgs)
> CMake Error at /usr/share/rostime/cmake/rostimeConfig.cmake:95 (message):
>   Project 'rostime' specifies
>   '/home/lukas/oe-core/build/tmp-eglibc/sysroots/qemux86-64/usr/include' as
>   an include dir, which is not found.  It does neither exist as an absolute
>   directory nor in
>   '/usr//home/lukas/oe-core/build/tmp-eglibc/sysroots/qemux86-64/usr/include'.
>   Ask the maintainer 'Dirk Thomas dthomas@willowgarage.com' to fix it.
> Call Stack (most recent call first):
>   /usr/share/roscpp_serialization/cmake/roscpp_serializationConfig.cmake:151 (find_package)
>   /usr/share/message_runtime/cmake/message_runtimeConfig.cmake:151 (find_package)
>   /usr/share/std_msgs/cmake/std_msgsConfig.cmake:151 (find_package)
>   /usr/share/catkin/cmake/catkinConfig.cmake:72 (find_package)
>   ros_chatter-master/chatter_msgs/CMakeLists.txt:4 (find_package)
> 
> -- Configuring incomplete, errors occurred!
> Invoking "cmake" failed

The dev packages still have some hard-coded pathes in the cmake files. This disallows to use the dev packages in any other environment than the build system.

**Comment by herb-kuta-lge** [comment]
This is not a supported use-case for OpenEmbeded. @bulwahn  < Can this issue be closed?

**Comment by herb-kuta-lge** [comment]
"Silence implies consent" (see http://wiki.c2.com/?SilenceImpliesConsent).
