### ISSUE TITLE
Missing colcon in gatesgarth/milestones/16

### ISSUE THREAD

**Issue by thymbahutymba** [ros/meta-ros#1036]
#977 is missing on the gatesgarth/milestones/16. I need this version since my project still use the old syntax, therefore the branch gatesgarth does not build properly. How can I solve such issue? Thanks in advance.

**Comment by shr-project** [comment]
Update bitbake revision and use latest gatesgarth.

**Comment by thymbahutymba** [comment]
I'm actually using petalinux 2021.2.

**EDIT**

I saw that it has bitbake 1.48.0 and for parsing both the new and older syntax is required 1.48.4

**Comment by robwoolley** [comment]
Closing this issue as gatesgarth is no longer supported.
