### ISSUE TITLE
What's the license of the cache.yaml files?

### ISSUE THREAD

**Issue by JasonShigit** [ros/meta-ros#1042]
Hi team,
I want to use the yaml file with superflore to generate new recipes for humble. Need confirmation:

What's the explicit license of the generated cache.yaml file by ros-generate-cache.sh in meta-ros?

Hope you can confrim it, thanks a lot.

**Comment by robwoolley** [comment]
Hi @JasonShigit,

I don't know how to answer.  The existing files in the layer were contributed under the MIT license (see the COPYING.MIT file in the root of the repository).

However, I don't think that using the tool to generate a new cache.yaml imposes a specific license on it.

Hope that helps,
Rob
