### ISSUE TITLE
What's the license of the yaml files?

### ISSUE THREAD

**Issue by JasonShigit** [ros/meta-ros#1044]
Hi rosdistro team,

I want to use the yaml file with superflore to generate new recipes for humble. Need confirmation:

What's the explicit license of the generated cache.yaml file by ros-generate-cache.sh in meta-ros?

Hope you can confrim it, thanks a lot.

**Comment by JasonShigit** [comment]
hi team,
can you update on this issue?

**Comment by nuclearsandwich** [comment]
I have transferred this issue here since it is a question best answered by the meta-ros maintainers.

**Comment by robwoolley** [comment]
This appears to be a duplicate of #1042
