### ISSUE TITLE
Fetch error for rcss3d-agent

### ISSUE THREAD

**Issue by bchoineubility** [ros/meta-ros#1045]
Hi 
I am trying to build ros ditro galatic with raspberry pi.
By the way, there is a fetch error for rcss3d-agent.  

My mcf file is 
ros2-galatic-kirkstone.mcf

MACHINE is raspberrypi4

**To Reproduce**
You can reproduce with  
bitbake -c fetch rcss3d-agent

**Expected behavior**
bitbake -c fetch rcss3d-agent should fetch target repo.

**My opinion**
rcss3d-agent recipe is too old and you can see its repo deprecated. so, I think recipe updating is required.

BR,
Mark
[log.do_fetch.21764.txt](https://github.com/ros/meta-ros/files/12142519/log.do_fetch.21764.txt)

**Comment by robwoolley** [comment]
Thanks, Mark.

It looks as if this was automatically corrected in the latest changes I made for the newer releases:
$ find . -name rcss3d-agent_\* | xargs grep git:
./meta-ros2-galactic/generated-recipes/naosoccer-sim/rcss3d-agent_0.0.2-1.bb:SRC_URI = "git://github.com/ijnek/naosoccer_sim-release;${ROS_BRANCH};protocol=https"
./meta-ros2-humble/generated-recipes/rcss3d-agent/rcss3d-agent_0.2.1-1.bb:SRC_URI = "git://github.com/ros2-gbp/rcss3d_agent-release;${ROS_BRANCH};protocol=https"
./meta-ros2-rolling/generated-recipes/rcss3d-agent/rcss3d-agent_0.4.1-2.bb:SRC_URI = "git://github.com/ros2-gbp/rcss3d_agent-release;${ROS_BRANCH};protocol=https"
./meta-ros2-iron/generated-recipes/rcss3d-agent/rcss3d-agent_0.4.1-3.bb:SRC_URI = "git://github.com/ros2-gbp/rcss3d_agent-release;${ROS_BRANCH};protocol=https"

I don't intend to update galactic, which is unsupported, unless there is a compelling reason for it.

I appreciate you reporting this.

Regards,
Rob
