### ISSUE TITLE
Fetch error for openvslam

### ISSUE THREAD

**Issue by bchoineubility** [ros/meta-ros#1046]
**Describe the bug**
openvslam-0.2.3-3 recipe occur fetch error because openvslam is termiated officially. 

**To Reproduce**
bitbake -c fetch openvslam

**error log**
ERROR: openvslam-0.2.3-3-r0 do_fetch: Fetcher failure: Fetch command export PSEUDO_DISABLED=1; export PATH="/home/bchoi/nvidia-yocto-bsp/bchoi-build/tmp/sysroots-uninative/x86_64-linux/usr/bin:/home/bchoi/nvidia-yocto-bsp/sources/poky/scripts:/home/bchoi/nvidia-yocto-bsp/bchoi-build/tmp/work/armv8a-poky-linux/openvslam/0.2.3-3-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux:/home/bchoi/nvidia-yocto-bsp/bchoi-build/tmp/work/armv8a-poky-linux/openvslam/0.2.3-3-r0/recipe-sysroot/usr/bin/crossscripts:/home/bchoi/nvidia-yocto-bsp/bchoi-build/tmp/work/armv8a-poky-linux/openvslam/0.2.3-3-r0/recipe-sysroot-native/usr/sbin:/home/bchoi/nvidia-yocto-bsp/bchoi-build/tmp/work/armv8a-poky-linux/openvslam/0.2.3-3-r0/recipe-sysroot-native/usr/bin:/home/bchoi/nvidia-yocto-bsp/bchoi-build/tmp/work/armv8a-poky-linux/openvslam/0.2.3-3-r0/recipe-sysroot-native/sbin:/home/bchoi/nvidia-yocto-bsp/bchoi-build/tmp/work/armv8a-poky-linux/openvslam/0.2.3-3-r0/recipe-sysroot-native/bin:/home/bchoi/nvidia-yocto-bsp/sources/poky/bitbake/bin:/home/bchoi/nvidia-yocto-bsp/bchoi-build/tmp/hosttools"; export HOME="/home/bchoi"; LANG=C git -c core.fsyncobjectfiles=0 -c gc.autoDetach=false -c core.pager=cat clone --bare --mirror https://github.com/OpenVSLAM-Community/openvslam-release /home/bchoi/nvidia-yocto-bsp/bchoi-build/downloads/git2/github.com.OpenVSLAM-Community.openvslam-release --progress failed with exit code 128, no output
ERROR: openvslam-0.2.3-3-r0 do_fetch: Bitbake Fetcher Error: FetchError('Unable to fetch URL from any source.', 'git://github.com/OpenVSLAM-Community/openvslam-release;branch=release/galactic/openvslam;protocol=https')
ERROR: Logfile of failure stored in: /home/bchoi/nvidia-yocto-bsp/bchoi-build/tmp/work/armv8a-poky-linux/openvslam/0.2.3-3-r0/temp/log.do_fetch.2162
ERROR: Task (/home/bchoi/nvidia-yocto-bsp/sources/meta-ros/meta-ros2-galactic/generated-recipes/openvslam/openvslam_0.2.3-3.bb:do_fetch) failed with exit code '1'
NOTE: Tasks Summary: Attempted 1 tasks of which 0 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/bchoi/nvidia-yocto-bsp/sources/meta-ros/meta-ros2-galactic/generated-recipes/openvslam/openvslam_0.2.3-3.bb:do_fetch
Summary: There was 1 WARNING message.
Summary: There were 2 ERROR messages, returning a non-zero exit code.

**Expected behavior**
do_fetch action should be successful. to achieve it, you will upgrade openvslam recipes.  openvslam would survive at https://github.com/stella-cv/stella_vslam_ros.git.

BR,
Mark

**Comment by robwoolley** [comment]
Thanks for letting me know.  I checked the newer ROS distros and they don't have a recipe for openvslam (or for stella_vslam_ros).  I'm going to close this issue for now, but feel free to open a new one if you feel that we should have a recipe for stella_vslam_ros.

Regards,
Rob
