### ISSUE TITLE
How to add ROS2 foxy recipes to my image ?

### ISSUE THREAD

**Issue by Sbenbe** [ros/meta-ros#1054]
Hello Team,
I just built my B2QT image with yocto and It seems like my application needs also ROS2 to be installed. I tried to add some layers in my bblayers.conf but when I bitbake again nothing happned and it is not taking into account the added layers.
Any help please.
Thank you in advance. 

The "Build Configuration:" :
host machine: Ubunto 20.04
Target: Raspberry pi4

- bblayers.conf

BBLAYERS ?= " \
  ${BSPDIR}/sources/meta-ros/meta-ros-common \
  ${BSPDIR}/sources/meta-ros/meta-ros2 \
  ${BSPDIR}/sources/meta-ros/meta-ros2-foxy \
  ${BSPDIR}/sources/poky/meta \
  ${BSPDIR}/sources/poky/meta-poky \
  ${BSPDIR}/sources/meta-raspberrypi \
  ${BSPDIR}/sources/meta-openembedded/meta-oe \
  ${BSPDIR}/sources/meta-openembedded/meta-python \
  ${BSPDIR}/sources/meta-openembedded/meta-networking \
  ${BSPDIR}/sources/meta-openembedded/meta-initramfs \
  ${BSPDIR}/sources/meta-openembedded/meta-multimedia \
  ${BSPDIR}/sources/meta-boot2qt/meta-boot2qt \
  ${BSPDIR}/sources/meta-boot2qt/meta-boot2qt-distro \
  ${BSPDIR}/sources/meta-mingw \
  ${BSPDIR}/sources/meta-qt6 \
  "

- local.conf

ROS_DISTRO = "foxy"
 ROS_DOMAIN_ID = "0"

**Comment by vmayoral** [comment]
Your issues are don't seem `meta-ros` specific. @Sbenbe, you may want to learn a bit further your ways around OpenEmbedded/Yocto. See https://github.com/ros/meta-ros/wiki/OpenEmbedded-Build-Instructions
