### ISSUE TITLE
Remove meta-python2 as a dependency

### ISSUE THREAD

**Issue by robwoolley** [ros/meta-ros#1076]
As reported by Tim Orling:

> 
> We need to drop meta-python2 as a requirement. It will NOT be supported moving forward and should be considered DEAD after kirkstone. We have had more than 10 years warning. Any further support is just asking for vulnerabilities and security risks.
> 
> 
> - [PEP 373 – Python 2.7 Release Schedule | peps.python.org](https://peps.python.org/pep-0373/)
> - [Sunsetting Python 2](https://www.python.org/doc/sunset-python-2/)
> 
> This means meta-ros-python2 and meta-ros1-melodic should be dropped (including from langdale, mickledore and nanbield).
> 
> - https://layers.openembedded.org/layerindex/updates/38574/
> 
> meta-ros1-melodic is also still using DEPRECATED distutils-common-base.bbclass:
> - https://layers.openembedded.org/layerindex/updates/38576/

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-openembedded-working-group-2023-12-11-3pm-utc/34691/4

**Comment by robwoolley** [comment]
meta-ros-python2 has been removed: https://github.com/ros/meta-ros/commit/4775ec30a91613e608875636fcef7469f91efce0
