### ISSUE TITLE
meta-ros on jetson-nano-devkit

### ISSUE THREAD

**Issue by salmaibrahimelsayed** [ros/meta-ros#1139]
The machine which I'm building for is jetson-nano-devkit and scarthgap doesn't support it only kirkstone 
when I try to bitbake core-image-base
after adding meta-ros layer to bblayers.conf 
it says 
ERROR: Layer ros1-noetic-layer is not compatible with the core layer which only supports these series: kirkstone (layer is compatible with scarthgap)

What can I do?

**Comment by robwoolley** [comment]
Hi @salmaibrahimelsayed,

It sounds like you need to check out the kirkstone branch.  You will need to add 3 entries to your bblayers.conf:  meta-ros-common, meta-ros1, meta-ros1-noetic

In the past only qemux86-64 and Raspberry Pi SBCs were officially supported.  However, everything should work fine on other boards.

Regards,
Rob

**Comment by robwoolley** [comment]
Hi @salmaibrahimelsayed,

I created a kas configuration for The Nvidia Orin Nano devkit: (https://github.com/ros/meta-ros/blob/build/kas/oeros-kirkstone-humble-jetson-orin-nano-devkit.yml).

You can use it to build ROS 2 Humble for Kirkstone for the Nvidia Jetson Orin Nano Devkit by following these instructions: https://github.com/ros/meta-ros/blob/build/kas/README.md

I would encourage you to start with ROS 2, but if you want noetic then just make a copy of the file and replace "humble" with "noetic" in the filename and on line 5.

Let me know if that helps!

Regards,
Rob
