### ISSUE TITLE
HOST path is included in urdfdom package

### ISSUE THREAD

**Issue by jiaxshi** [ros/meta-ros#1166]
**Describe the bug**
HOST path is included in urdfdom package. Submit an issue for tracking this issue. Will try to fix it and raise a PR.

**Log**
usr/lib/urdfdom/cmake/urdfdomExport.cmake:67:  INTERFACE_INCLUDE_DIRECTORIES "/local/mnt3/workspace/jiaxshi/projects/external/build-qcom-wayland/tmp-glibc/work/armv8-2a-qcom-linux/urdfdom/3.0.2-2-r0/recipe-sysroot/usr/include;${_IMPORT_PREFIX}/include/urdfdom"

**Comment by robwoolley** [comment]
Closed as resolved.
