### ISSUE TITLE
meta-ros2-jazzy is not available for krogoth branch

### ISSUE THREAD

**Issue by sushmad16** [ros/meta-ros#1209]
I am currently using the Krogoth branch of OpenEmbedded and would like to integrate the meta-ros2-jazzy layer. However, it appears that meta-ros2-jazzy is not available for this branch.

Could you please confirm if there are plans to support meta-ros2-jazzy for the Krogoth branch? If not, are there any recommended alternatives for integrating ROS2 Jazzy with Krogoth?

**Comment by robwoolley** [comment]
Sorry, the Krogoth branch of OpenEmbedded was last released in July 2017 and is officially End-of-Life: https://wiki.yoctoproject.org/wiki/Releases
