### ISSUE TITLE
Ompl 1.6.0-1 Bitbake Append

### ISSUE THREAD

**Issue by collinbrake** [ros/meta-ros#1237]
**Describe the bug**

Building ompl is failing:
```bash
...
| -- Installing: /build/tmp/work/cortexa72-cortexa53-crypto-ttcontrol-linux/ompl/1.6.0-1/image/opt/ros/humble/share/man/man1/plannerarena.1
| open: No such file or directory
| elf_open: Invalid argument
| WARNING: exit code 1 from a shell command.
ERROR: Task (/build/../work/sources/meta-ros/meta-ros2-humble/generated-recipes/ompl/ompl_1.6.0-1.bb:do_install) failed with exit code '1'
NOTE: Tasks Summary: Attempted 1713 tasks of which 1712 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /build/../work/sources/meta-ros/meta-ros2-humble/generated-recipes/ompl/ompl_1.6.0-1.bb:do_install
Summary: There was 1 ERROR message, returning a non-zero exit code.
```

From the looks of things this is due to an append file left over from a previous version of ompl: https://github.com/ros/meta-ros/blob/650e92f8e77d31f2db6e4f8de16527c053211675/meta-ros2-humble/recipes-bbappends/ompl/ompl_%25.bbappend#L27

**To Reproduce**

TUNE_FEATURES        = "aarch64 crc cortexa72-cortexa53 crypto"
ROS_DISTRO           = "humble"
ROS_VERSION          = "2"
ROS_PYTHON_VERSION   = "3"
meta-freescale       = "HEAD:1444416aeb875d5b62008aaf31a5cb6b596cc41a"
meta-freescale-distro = "HEAD:b9d6a5d9931922558046d230c1f5f4ef6ee72345"
meta-kf6             = "HEAD:d710d44c058c342dac45d49ad413867cae432d7f"
meta-multimedia      
meta-networking      
meta-oe              
meta-python          
meta-webserver       = "HEAD:4a7bb77f7ebe0ac8be5bab5103d8bd993e17e18d"
meta-qt6             = "HEAD:9c396cfd8dadb81d4844d1e0599bd6ec7b84824f"
meta-ros-common      
meta-ros2            
meta-ros2-humble     = "HEAD:b96ba3d66488aca5868fa1a94643a7f52b2cfc07"
meta-swupdate        = "HEAD:a924d4bfd9dd54638ac8348d3f2845339f789770"
meta                 
meta-poky            
meta-yocto-bsp       = "patched-f7def85be9f99dcb4ba488bead201f670304379b:26fd36f4fac10a9285d72fdd247246ee4681c1ae"

**Comment by mark-bchoi** [comment]
Hi, 

I can not see this issue in building ompl-1.6.0. and bbappend file do not have such line. 

```
bchoi@ubuntu-22:~/nvidia-yocto-bsp/layers$ cat ./meta-ros/meta-ros2-humble/recipes-bbappends/ompl/ompl_%.bbappend
# Copyright (c) 2021 LG Electronics, Inc.

# used only as runtime dependency, but there is no ode/libode recipe, try to set it empty to test in runtime if this new dependency from 1.5.2 version is really mandatory
# https://github.com/ompl/ompl/compare/1.5.1...1.5.2
# https://github.com/ompl/ompl/commit/bb0a03c6fe4fbba0282c9a58881c3f499e7564d0 says it's optional
ROS_UNRESOLVED_DEP-opende = ""

# ERROR: ompl-1.5.2-1-r0 do_package: QA Issue: ompl: Files/directories were installed but not shipped in any package:
#   /usr/share/ament_index
#   /usr/share/ament_index/resource_index
#   /usr/share/ament_index/resource_index/packages
#   /usr/share/ament_index/resource_index/packages/ompl
# Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
# ompl: 4 installed and not shipped files. [installed-vs-shipped]
#
# ros_ament_cmake.bbclass does this automatically, but this recipe inherits just ros_cmake.bbclass
FILES:${PN}:prepend = " \
    ${datadir}/ament_index \
"

# ERROR: ompl-1.5.2-1-r0 do_package_qa: QA Issue: non -dev/-dbg/nativesdk- package ompl contains symlink .so '/usr/lib/libompl.so' [dev-so]
inherit ros_insane_dev_so

# ERROR: ompl-1.5.2-1-r0 do_package_qa: QA Issue: ompl: /usr/lib/libompl.so.1.5.2 contains probably-redundant RPATH /usr/lib [useless-rpaths]
DEPENDS:append:class-target = " chrpath-replacement-native"
#do_install:append() {
#    chrpath --delete ${D}${libdir}/*${SOLIBS}
#}

FILESEXTRAPATHS:prepend := "${THISDIR}/${BPN}:"
SRC_URI += "file://0001-FindPython.cmake-install_python-Allow-to-set-differe.patch"

EXTRA_OECMAKE += "-DINSTALL_PYTHON_SHEBANG='/usr/bin/env python3'"

```

Is there any misunderstand for this issue?

BR,
Mark

**Comment by robwoolley** [comment]
@collinbrake Thanks for reporting this.  Am I correct in assuming that this is with scarthgap?  I will try to reproduce it myself to see if I see it as well.

**Comment by collinbrake** [comment]
@robwoolley Sorry for the delayed response. Yes, this is on scarthgap.

Now I can't reproduce the issue either. Closing.
