### ISSUE TITLE
kirkstone: ros2 humble: canopen-interfaces_0.2.11-2: problems when populating sdk

### ISSUE THREAD

**Issue by graceagrace** [ros/meta-ros#1239]
Hi there,

I've managed to create a patch that integrates ROS2 humble into the SDK, and am now trying to compile `canopen-core` as part of the libraries on the target. I am running into issues with `canopen-interfaces` and get the following build error:
```
| -- Found rosidl_default_generators: 1.2.0 (build/tmp/work/armv8a-linux/canopen-interfaces/0.2.11-2-r0/recipe-sysroot/usr/share/rosidl_default_generators/cmake)
| CMake Error at build/tmp/work/armv8a-linux/canopen-interfaces/0.2.11-2-r0/recipe-sysroot/usr/share/rosidl_default_generators/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package):
|   By not providing "Findrosidl_cmake.cmake" in CMAKE_MODULE_PATH this project
|   has asked CMake to find a package configuration file provided by
|   "rosidl_cmake", but CMake did not find one.
| 
|   Could not find a package configuration file provided by "rosidl_cmake" with
|   any of the following names:
| 
|     rosidl_cmakeConfig.cmake
|     rosidl_cmake-config.cmake
| 
|   Add the installation prefix of "rosidl_cmake" to CMAKE_PREFIX_PATH or set
|   "rosidl_cmake_DIR" to a directory containing one of the above files.  If
|   "rosidl_cmake" provides a separate development package or SDK, be sure it
|   has been installed.
```
It seems like adding `rosidl-cmake` as a build dependency would resolve this error, but it does not, and I end up getting an error downstream where the .srv files are not build properly and cannot be found by `canopen-core`. I am a bit stuck on what to try next - the `.bbappend` file applied to the `canopen-interfaces` recipe for ROS2 Rolling did not resolve the problem, either, and gives me a wall of error text, including the following:
`| FAILED: libcanopen_interfaces__rosidl_generator_c.so`

Has anyone encountered similar problems with `ros2-canopen`?

**Comment by mark-bchoi** [comment]
Hi, 

I did reproduce this issue and could clear it by adding rosidl-cmake-native now.

BR,
Mark

**Comment by graceagrace** [comment]
Thanks Mark, this worked for me! I greatly appreciate your help.
