### ISSUE TITLE
check style of recipes

### ISSUE THREAD

**Issue by bulwahn** [ros/meta-ros#16]
The created recipes should follow the style defined in
https://wiki.yoctoproject.org/wiki/Recipe_%26_Patch_Style_Guide
and
http://www.openembedded.org/wiki/Styleguide.
Possibly make checking the style part of some testing process.

**Comment by herb-kuta-lge** [comment]
@bulwahn < Can this issue be closed?

**Comment by herb-kuta-lge** [comment]
"Silence implies consent" (see http://wiki.c2.com/?SilenceImpliesConsent).
