### ISSUE TITLE
roscpp-serialization dependency in *-msgs recipes

### ISSUE THREAD

**Issue by bulwahn** [ros/meta-ros#170]
message packages that depend on other message packages require the roscpp-serialization package when building.

todo: example
- how do we want to take care of this in the meta-ros recipes.
- discuss how this is represented in ROS package.xml (and how this could be represented in general)

**Comment by herb-kuta-lge** [comment]
This appears to no longer be the case, @bulwahn < Can this issue be closed?

**Comment by herb-kuta-lge** [comment]
"Silence implies consent" (see http://wiki.c2.com/?SilenceImpliesConsent).
