### ISSUE TITLE
x264: libx264.so.133 has relocations in .text

### ISSUE THREAD

**Issue by bulwahn** [ros/meta-ros#196]
WARNING: QA Issue: ELF binary '/home/lukas/tmp-build/openembedded-core/tmp-eglibc/work/cortexa9hf-vfp-oe-linux-gnueabi/x264/r2265+gitAUTOINC+585324fee3-r0/packages-split/x264/usr/lib/libx264.so.133' has relocations in .text

**Comment by bulwahn** [comment]
This warning `WARNING: x264-r2491+gitAUTOINC+86b71982e1-r0 do_package_qa: QA Issue: ELF binary '/home/lukas/dev/openembedded.org/openembedded-core/build/tmp-glibc/work/i586-oe-linux/x264/r2491+gitAUTOINC+86b71982e1-r0/packages-split/x264/usr/lib/libx264.so.148' has relocations in .text [textrel]` is still emitted with the build configuration:
```
BB_VERSION        = "1.32.0"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "fedora-23"
TARGET_SYS        = "i586-oe-linux"
MACHINE           = "qemux86"
DISTRO            = "nodistro"
DISTRO_VERSION    = "nodistro.0"
TUNE_FEATURES     = "m32 i586"
TARGET_FPU        = ""
meta              = "master:11063a01d4511b2688ea7ba2d7359e4e07328c66"
meta-oe           
meta-python       
meta-multimedia   = "master:18d518a03d7d55b69f7ff4b19916c7006220c3e9"
meta-intel-realsense = "master:c74766ff2dc7383562bdd4aa1f10687c94261c53"
meta-ros          = "master:0a9f44d830f1c4fa560c5b8eabb02ff0706c9b00"
```

**Comment by herb-kuta-lge** [comment]
@bulwahn < Can this issue be closed?

**Comment by herb-kuta-lge** [comment]
"Silence implies consent" (see http://wiki.c2.com/?SilenceImpliesConsent).
