### ISSUE TITLE
Gumstix Yocto-Dora Bitbake error

### ISSUE THREAD

**Issue by MarkusEich** [ros/meta-ros#233]
I am on Yocto-Dora with gumstix.

The bblayers.conf looks like

BBPATH = "${TOPDIR}"
BBFILES ?= ""
BBLAYERS ?= " \
  /home/eich/yocto/poky/meta \
  /home/eich/yocto/poky/meta-yocto \
  /home/eich/yocto/poky/meta-openembedded/meta-gnome \
  /home/eich/yocto/poky/meta-openembedded/meta-oe \
  /home/eich/yocto/poky/meta-openembedded/meta-xfce \
  /home/eich/yocto/poky/meta-openembedded/meta-systemd \
  /home/eich/yocto/poky/meta-openembedded/meta-networking \
  /home/eich/yocto/poky/meta-openembedded/meta-multimedia \
  /home/eich/yocto/poky/meta-gumstix \
  /home/eich/yocto/poky/meta-gumstix-extras \
  /home/eich/yocto/poky/meta-ros \
  "

running  bitbake core-image-ros-roscore results in
ERROR: No recipes available for:
  /home/eich/yocto/poky/meta-ros/recipes-support/boost/boost_%.bbappend
ERROR: Command execution failed: Exited with 1

Seems that I have problems with the wildcard in boost_%.bbappend.

Renaming  boost_%.bbappend to boost_1.54.0.bbappend (the one shipping with yocto dora) seems to start building.

Is this a bug or am I missing something?

**Comment by bulwahn** [comment]
As nobody has reported about this issue again, the solution to this issue for Gumstix and similar distributions seem to adequately documented. Hence, I am closing this issue now.
