### ISSUE TITLE
error: package update-rc.d is not installed when using ros-meta with yocto dora

### ISSUE THREAD

**Issue by MarkusEich** [ros/meta-ros#236]
I have a problem baking my ros image with dora. The build process looks good, until the install process starts. 

I used this configuration:
# 

Build Configuration:
BB_VERSION        = "1.20.0"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "Ubuntu-13.10"
TARGET_SYS        = "arm-poky-linux-gnueabi"
MACHINE           = "overo"
DISTRO            = "poky"
DISTRO_VERSION    = "1.5.1"
TUNE_FEATURES     = "armv7a vfp neon"
TARGET_FPU        = "vfp-neon"
meta  
meta-yocto        = "(detachedfromyocto/dora):d0e55dd0ef92fef31976edfb920a021c313fa14e"
meta-gnome  
meta-oe  
meta-xfce  
meta-systemd  
meta-networking  
meta-multimedia   = "(detachedfrom40e0f37):40e0f371f3eb1628655c484feac0cebf810737b4"
meta-gumstix      = "(detachedfrom1d5ef1f):1d5ef1f64ad876c9a0aa7c1fce792a682166d97b"
meta-gumstix-extras = "(detachedfrom457a584):457a5842cb5831fd68184f5d2a7805759076f548"
meta-ros          = "master:097668a6dc955511b58f20ef12fcea96ac333874"
# 

Calling butbake core-image-ros-roscore produced the following error:

```
Running intercept scripts:
WARNING: The license listed MIT was not in the licenses collected for packagegroup-core-boot
log_check: Using /home/eich/yocto/gumstix_ros_build/tmp/work/overo-poky-linux-gnueabi/core-image-ros-roscore/1.0-r0/temp/log.do_rootfs.26010 as logfile
Logfile is clean
error: package update-rc.d is not installed
WARNING: exit code 1 from a shell command.
ERROR: Function failed: do_rootfs (log file is located at /home/eich/yocto/gumstix_ros_build/tmp/work/overo-poky-linux-gnueabi/core-image-ros-roscore/1.0-r0/temp/log.do_rootfs.26010)
```

I tracked the issue down to the file core-image-ros-roscore.bb

This contains the line

 # remove not needed ipkg informations
ROOTFS_POSTPROCESS_COMMAND += "remove_packaging_data_files"

 This causes the problem. I commented the line and now everything build
 fine.

Baked image boots without problem.

Cheers,

Markus

**Comment by bulwahn** [comment]
I close this issue because the commit 3e4f257d5e840bf0858e842059758569c956ce87 has removed the two critical lines in the image recipes.
