### ISSUE TITLE
handle runtime dependencies of python modules in message recipes

### ISSUE THREAD

**Issue by bulwahn** [ros/meta-ros#240]
The message recipes, e.g. std-msgs, geometry-msgs, nav-msgs, provide the msg files (in usr/share/ of the common package), the C headers (only in the dev-package) and the generated python modules.
Some ROS packages depend on the C headers for the compilation, other ROS packages depend during the run time on the python modules.
If messages depend on other messages, the corresponding recipes must add a DEPENDS for the other message for the C headers, and a RDEPENDS for the python modules. This was discovered in a recent commit [1].

To keep the image as small as possible, shall we split the message recipes into separate packages (e.g. '...-plain' for only the msg file, and '...-python' for the python files) and explicitly add the runtime dependencies to those packages?

[1] https://github.com/bmwcarit/meta-ros/commit/997876732d2f09164da1f82b7a7be75950e0d151

**Comment by herb-kuta-lge** [comment]
@bulwahn < Can this issue be closed?

**Comment by herb-kuta-lge** [comment]
"Silence implies consent" (see http://wiki.c2.com/?SilenceImpliesConsent).
