### ISSUE TITLE
ivcon: No generic license file exists for: GPL in any provider

### ISSUE THREAD

**Issue by bulwahn** [ros/meta-ros#264]
The file in ivcon.c in the ivcon repository contains no license information and the repository contains no license file. The origin of the file must be determined and a license file must be added to the repository.

**Comment by shr-project** [comment]
This one is a bit tricky because ivcon-0.1.5/src/ivcon.cpp actually says 137 times LGPL:

//    This code is distributed under the GNU LGPL license.

**Comment by herb-kuta-lge** [comment]
`ivcon` successfully builds for **melodic** using `[thud-draft]`, with no complaints about its `LICENSE` value. @bulwahn < Can I close this issue?

**Comment by herb-kuta-lge** [comment]
"Silence implies consent" (see http://wiki.c2.com/?SilenceImpliesConsent).
