### ISSUE TITLE
making a recipe for a ROS package (or four)

### ISSUE THREAD

**Issue by fbstj** [ros/meta-ros#266]
Hey. I'd like to make a recipe for [ros_arduino_bridge](https://github.com/hbrobotics/ros_arduino_bridge) but I have no idea how to even start, or make it work, or test it without breaking the whole previous build. does anyone have any suggestions?

**Comment by bulwahn** [comment]
I have added recipes for the git version of ros_arduino_bridge in the commit https://github.com/bulwahn/meta-ros/commit/20a1e98a36aff31860d216c6b0151980dc58b8bb. I think when this commit is merged, we can now close this issue.

**Comment by bulwahn** [comment]
As I believe that the issue has been resolved, I close it now.
