### ISSUE TITLE
failed to build ros-world

### ISSUE THREAD

**Issue by fbstj** [ros/meta-ros#267]
> $~/devel/build$ bitbake core-image-ros-world
> Loading cache: 100% |###########################################| ETA: 00:00:00
> Loaded 1994 entries from dependency cache.
> NOTE: Resolving any missing task queue dependencies
> ERROR: Nothing PROVIDES 'libav' (but /home/peter/devel/meta-openembedded/meta-oe/recipes-support/opencv/opencv_2.4.bb DEPENDS on or otherwise requires it)
> ERROR: libav was skipped: because it has a restricted license not whitelisted in LICENSE_FLAGS_WHITELIST
> ERROR: libav was skipped: because it has a restricted license not whitelisted in LICENSE_FLAGS_WHITELIST
> NOTE: Runtime target 'compressed-image-transport' is unbuildable, removing...
> Missing or unbuildable dependency chain was: ['compressed-image-transport', 'cv-bridge', 'opencv', 'libav']
> NOTE: Runtime target 'packagegroup-ros-world' is unbuildable, removing...
> Missing or unbuildable dependency chain was: ['packagegroup-ros-world', 'compressed-image-transport', 'cv-bridge', 'opencv', 'libav']
> ERROR: Required build target 'core-image-ros-world' has no buildable providers.
> Missing or unbuildable dependency chain was: ['core-image-ros-world', 'packagegroup-ros-world', 'compressed-image-transport', 'cv-bridge', 'opencv', 'libav']
> 
> Summary: There were 2 ERROR messages shown, returning a non-zero exit code.

**Comment by bulwahn** [comment]
Compiling the PCL library needs a lot of CPU power and memory. If you build PCL on a machine that just does not provide the needed ressources, it will start thrashing and the build will take longer than anyone would accept.

I am closing the issue because there is nothing we can do in the meta-ros layer here.
