### ISSUE TITLE
speech-tools: No rule to make target `../lib/libeststring.a' in do_compile

### ISSUE THREAD

**Issue by bulwahn** [ros/meta-ros#278]
On a clean build, `bitbake speech-tools` fails with:

make[1]: **\* No rule to make target `../lib/libestbase.a', needed by`xml_example'.  Stop.
make[1]: **\* No rule to make target `../lib/libeststring.a', needed by`ch_lab'.  Stop.

at commits:
meta = "master:b4cd268cf7506a521d7800112cb775bd49e1ef09"
meta-oe = "master:e988ed754ba2d18d8f08903d0a034b64f169bd4a"
meta-ros = "master:3954c3960a0d371ff98b9bcbef3f7e4843d129d6" (with autotools-brokensep in speech-tools recipe)

After restarting `bitbake speech-tools` again, the problem disappears, but then the issue #279 appears.

**Comment by herb-kuta-lge** [comment]
@bulwahn < Can this issue be closed?

**Comment by herb-kuta-lge** [comment]
"Silence implies consent" (see http://wiki.c2.com/?SilenceImpliesConsent).
