### ISSUE TITLE
do_compile on boost_1.56.0.bb fails with exit code '1'

### ISSUE THREAD

**Issue by aehernandez** [ros/meta-ros#296]
Hello everyone,
I'm new to the open-embedded and bitbake toolchain and I've been trying to write my own recipes to cross compile onto a Beaglebone Black from Ubuntu. While trying to run `bitbake imu-filter` to create a package for my embedded ROS Hydro image, I receive the error `ERROR: Task 787 (/home/sda/devel/openembedded-core/meta/recipes-support/boost/boost_1.56.0.bb, do_compile) failed with exit code '1'`.

This is trying to build [this custom recipe](https://raw.githubusercontent.com/surveycorps/c_apro/master/recipes-apro/imu-filter/imu-filter_1.0.0.bb). The full log file output can be viewed here: http://pastebin.com/sVmjA4yi

I've had trouble trying to build boost on the target system before too. It always seems to give me errors. I'm not quite sure what boost is doing, or what its used for, as the source for the recipe doesn't belong to me. However, boost is not an immediate dependency of this particular package.

Can anyone help me resolve this issue? Thank you for your time!

**Comment by bulwahn** [comment]
@aehernandez Without any further information, I could not re-construct this problem. I assume this problem has been resolved by now.
