### ISSUE TITLE
systemd roscore.service use wrong environment

### ISSUE THREAD

**Issue by simkim** [ros/meta-ros#307]
When installing roslaunch-systemd from roslaunch recipe, the systemd configuration don't seems to match installed environnement.
- It use variable in variable for systemd which is not supported ( http://www.freedesktop.org/software/systemd/man/systemd.exec.html#Environment= )
- It miss PYTHONPATH, PATH, LD_LIBRARY_PATH variables
- It use /usr/bin/roscore instead of /opt/ros/hydro/bin/roscore

**Comment by bulwahn** [comment]
Now, as the pull request #308 has been merged, this issue is resolved. @simkim Can you confirm this and close the issue?

**Comment by bulwahn** [comment]
As I believe that the issue has been resolved, I close it now.
