### ISSUE TITLE
describe network configuration setup in OpenEmbedded user manual

### ISSUE THREAD

**Issue by bulwahn** [ros/meta-ros#339]
For meta-ros, the user must set up the network configuration. We would like to have a section in the OpenEmbedded user manual that describes how to do this. We can then refer to this section.

This was discussed in the abandoned pull request #258, which provides the minimal technical solution as commits.

**Comment by herb-kuta-lge** [comment]
`DISTRO` = `ros1` or `ros2` images now include **connman**, which means that Ethernet networking is automatically started.

@bulwahn < Can this issue be colsed?

**Comment by herb-kuta-lge** [comment]
"Silence implies consent" (see http://wiki.c2.com/?SilenceImpliesConsent).
