### ISSUE TITLE
Add doc job on rosdistro index?

### ISSUE THREAD

**Issue by 130s** [ros/meta-ros#357]
Having page(s) on wiki.ros.org increase chance for ROS software to be found tremendously IMO. I know meta-ros isn't in release-able form by its nature but its wiki page can still be generated automatically.

To do so I've already made a change that is [stored on my repo](https://github.com/130s/rosdistro/commit/3cf1b73598f45aa9c6c6b809fa157dea082d5d8f). If it's good I'll open a pull request against https://github.com/ros/rosdistro

**Comment by bulwahn** [comment]
If it helps, go ahead and do so.

**Comment by 130s** [comment]
Thanks, done https://github.com/ros/rosdistro/pull/9586
