### ISSUE TITLE
festival: QA Issue: host contamination

### ISSUE THREAD

**Issue by bulwahn** [ros/meta-ros#361]
WARNING: QA Issue: festival: /festival/usr/share/festival/voices/english/kal_diphone/festvox/kaldurtreeZ.scm is owned by uid 1008, which is the same as the user running bitbake. This may be due to host contamination [host-user-contaminated]

**Comment by herb-kuta-lge** [comment]
@bulwahn < Can this issue be closed?

**Comment by herb-kuta-lge** [comment]
"Silence implies consent" (see http://wiki.c2.com/?SilenceImpliesConsent).

**Comment by shr-project** [comment]
Also fixed in milestone 12.
