### ISSUE TITLE
Poco available in meta-openembedded

### ISSUE THREAD

**Issue by bachp** [ros/meta-ros#377]
Poco is now available in meta-openembedded: https://github.com/openembedded/meta-openembedded/tree/master/meta-oe/recipes-support/poco

I think it would be good to coordinate our efforts so there is only one recipe.

**Comment by bulwahn** [comment]
Thanks for the pointer. I will check if meta-ros runs with the meta-openembedded recipe.

**Comment by bulwahn** [comment]
This issue was addressed in https://github.com/bmwcarit/meta-ros/commit/02582cf1a0c2f00864f5e03bf5749b15af1d635d.

At some point in time, we can probably safely delete the duplicate poco recipe in meta-ros.
