### ISSUE TITLE
sphinxbase: QA Issue: rdepends on libasound [build-deps]

### ISSUE THREAD

**Issue by bulwahn** [ros/meta-ros#441]
`WARNING: sphinxbase-0.8-r0 do_package_qa: QA Issue: sphinxbase rdepends on libasound, but it isn't a build dependency, missing alsa-lib in DEPENDS or PACKAGECONFIG? [build-deps]`

**Comment by herb-kuta-lge** [comment]
@bulwahn < Can this issue be closed?

**Comment by herb-kuta-lge** [comment]
"Silence implies consent" (see http://wiki.c2.com/?SilenceImpliesConsent).
