### ISSUE TITLE
python-nose conflicts with python3-nose 

### ISSUE THREAD

**Issue by yongli3** [ros/meta-ros#458]
During the ros-world build, there is a conflict about python-nose and python3-nose. Since opencv dpeneds on python3-nose, by tf and rostest depend on python-nose. bitbake will install both of python3-nose and python-nose, this causes the ""that file is already provided by package" error message.

I think we need to change the python-nose to python3-nose in the DEPENDS in meta-ros

**Comment by bulwahn** [comment]
Thanks for reporting this issue. I am happy to review pull requests that address this issue. We should make sure that all ROS packages still work with python3, which sounds like a quite large task to me right now, but we will see once we start tackling this issue.

**Comment by yongli3** [comment]
Thanks @bulwahn, please check on PR #459

**Comment by yongli3** [comment]
As a workaround, we can modify the local.conf to disable python3 in opencv:
PACKAGECONFIG_remove_pn-opencv = " python3"
PACKAGECONFIG_append_pn-opencv = " python"

**Comment by rojkov** [comment]
I guess I'm volunteering to check if python3 is enough for ROS because the project I'm working on [1] wants to get rid of python2 completely.

[1] https://github.com/intel/intel-iot-refkit/

**Comment by bulwahn** [comment]
Well that sounds like a bigger task...

**Comment by bulwahn** [comment]
@yongli3 We have now included python3 support. Could you try if the issue still occurs in your image build when you set meta-ros to use python3?
