### ISSUE TITLE
PYTHONPATH in roscore systemd service file

### ISSUE THREAD

**Issue by mcopejans** [ros/meta-ros#503]
The PYTHONPATH in the [EnvironmentFile](https://github.com/bmwcarit/meta-ros/blob/master/recipes-ros/ros-comm/roslaunch/roscore-default) of [roscore.service](https://github.com/bmwcarit/meta-ros/blob/master/recipes-ros/ros-comm/roslaunch/roscore.service#L6) should be 
`/opt/ros/kinetic/lib/python2.7/dist-packages/` instead of `/opt/ros/kinetic/lib/python2.7/site-packages/`.

**Comment by bulwahn** [comment]
Feel free to open a pull request with your proposed change.
