### ISSUE TITLE
bfl: do_compile fails with error: 'make_array' is not a member of 'boost::serialization'

### ISSUE THREAD

**Issue by johannesschrimpf** [ros/meta-ros#510]
When compiling core-image-ros-world, bfl does not compile. Log file is attached.
[log.do_compile.4287.txt](https://github.com/bmwcarit/meta-ros/files/1004402/log.do_compile.4287.txt)

$ bitbake core-image-ros-world
Parsing recipes: 100% |#########################################################################################################################################################################| Time: 0:00:15
Parsing of 2169 .bb files complete (0 cached, 2169 parsed). 2930 targets, 175 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies

Build Configuration:
BB_VERSION        = "1.34.0"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "ubuntu-16.04"
TARGET_SYS        = "i586-oe-linux"
MACHINE           = "qemux86"
DISTRO            = "nodistro"
DISTRO_VERSION    = "nodistro.0"
TUNE_FEATURES     = "m32 i586"
TARGET_FPU        = ""
meta              = "master:c59fa3bd71b42410bf032846ee8fdb6e6eb1b95c"
meta-oe           
meta-python       
meta-multimedia   = "master:fc03b3d9382dd5b6a8fff5f84e4c86a1acc9a73a"
meta-ros          = "master:36eb1dd4f23f4a65827aea12258b4fbc7f751dc1"

Initialising tasks: 100% |######################################################################################################################################################################| Time: 0:00:22
NOTE: Executing SetScene Tasks
NOTE: Executing RunQueue Tasks
WARNING: imu-transformer-0.2.2-r0 do_populate_lic: imu-transformer: No generic license file exists for: GPL in any provider
WARNING: ivcon-0.1.5-r0 do_populate_lic: ivcon: No generic license file exists for: GPL in any provider
WARNING: rocon-ebnf-0.1.23-r0 do_populate_lic: rocon-ebnf: No generic license file exists for: GPL in any provider
ERROR: bfl-0.7.0-6-r0 do_compile: oe_runmake failed
ERROR: bfl-0.7.0-6-r0 do_compile: Function failed: do_compile (log file is located at /data/meta-ros/build/tmp-glibc/work/i586-oe-linux/bfl/0.7.0-6-r0/temp/log.do_compile.4287)
ERROR: Logfile of failure stored in: /data/meta-ros/build/tmp-glibc/work/i586-oe-linux/bfl/0.7.0-6-r0/temp/log.do_compile.4287

**Comment by rojkov** [comment]
This seems to be a dup of https://github.com/bmwcarit/meta-ros/issues/505
