### ISSUE TITLE
Build failure due to checksum mismatch

### ISSUE THREAD

**Issue by bharath374** [ros/meta-ros#552]
I started getting the following checksum failure today:
`
bitbake yaml-cpp
...
ERROR: Fetcher failure for URL: 'https://github.com/jbeder/yaml-cpp/archive/release-0.5.3.tar.gz'. Checksum mismatch!
File: '.../downloads/release-0.5.3.tar.gz' has md5 checksum e2507c3645fc2bec29ba9a1838fb3951 when 64200ca0bf5e0af065804d8d3e8f6d42 was expected
File: '.../downloads/release-0.5.3.tar.gz' has sha256 checksum 3492d9c1f4319dfd5588f60caed7cec3f030f7984386c11ed4b39f8e3316d763 when ac50a27a201d16dc69a881b80ad39a7be66c4d755eda1f76c3a68781b922af8f was expected
If this change is expected (e.g. you have upgraded to a new version without updating the checksums) then you can use these lines within the recipe:
SRC_URI[md5sum] = "e2507c3645fc2bec29ba9a1838fb3951"
SRC_URI[sha256sum] = "3492d9c1f4319dfd5588f60caed7cec3f030f7984386c11ed4b39f8e3316d763"
`
 
If one does a wget of the 'https://github.com/jbeder/yaml-cpp/archive/release-0.5.3.tar.gz” and do an md5sum, it does show a different string (e2507c3645fc2bec29ba9a1838fb3951) than the one in the below recipe so it seems like that file may have possibly changed at the source:
https://github.com/bmwcarit/meta-ros/blob/master/recipes-devtools/yaml-cpp/yaml-cpp_0.5.3.bb

**Comment by rojkov** [comment]
The issue can be tracked down to https://github.com/libgit2/libgit2/issues/4343#issuecomment-328631745
I guess we should stop using the tarballs generated by github on the fly.
