### ISSUE TITLE
readv() and writev() error while compiling clients/roscpp/src/libros/transport/transport_udp.cpp

### ISSUE THREAD

**Issue by kraravin** [ros/meta-ros#612]
#include <sys/uio.h> is not included in the clients/roscpp/src/libros/transport/transport_udp.cpp.  Can you please add the following fix https://github.com/ros/ros_comm/pull/1105/files?

**Comment by herb-kuta-lge** [comment]
No longer happens in the [thud-draft] branch.  @kraravin < Can this issue be closed?

**Comment by herb-kuta-lge** [comment]
"Silence implies consent" (see http://wiki.c2.com/?SilenceImpliesConsent).
