### ISSUE TITLE
roscpp, boost 1.69 and warrior

### ISSUE THREAD

**Issue by OYTIS** [ros/meta-ros#618]
Greetings,

boost 1.69 has got it to thud branch of oe-core, so roscpp is broken now (see https://github.com/bmwcarit/meta-ros/issues/615). Is there any chance compatibility with thud can be restored, or do we have to downgrade to sumo now?

Thanks!

UPD: looks like dependency on boost::signals has been removed shortly from ros_comm/roscpp, but it hasn't been released yet, and meta-ros seems to be designed to use release tarballs. Waiting for a release then?

**Comment by aizelauna** [comment]
I confirm the issue. I have the same error on my side.

**Comment by aizelauna** [comment]
As a workaround, in my layer, I patched _roscpp_ with a bbappend recipe to remove signals from _find_package_ directive. 
_roscpp_ uses now signals2 which one is a header only component:
https://stackoverflow.com/questions/27252213/cmake-can-not-find-boostsignals2

**Comment by shr-project** [comment]
FYI: the upgrade will probably be reverted very soon from thud:
http://lists.openembedded.org/pipermail/openembedded-core/2019-March/280203.html

This issue is still valid for oe-core master (which will soon became warrior).

**Comment by shr-project** [comment]
Fixed in legacy branch.
