### ISSUE TITLE
ROS recipes for velodyne

### ISSUE THREAD

**Issue by marcelswz** [ros/meta-ros#628]
Th velodyne recipe can't download the source file. It is not in that archive

ERROR: velodyne-msgs-1.3.0-r0 do_fetch: Fetcher failure for URL: 'https://github.com/ros-drivers/velodyne/archive/velodyne-1.3.0.tar.gz;downloadfilename=velodyne-1.3.0.tar.gz'. Unable to fetch URL from any source

**Comment by monicuti** [comment]
Hello,

This happen to me too:

ERROR: velodyne-driver-1.3.0-r0 do_fetch: Fetcher failure for URL: 'https://github.com/ros-drivers/velodyne/archive/velodyne-1.3.0.tar.gz;downloadfilename=velodyne-1.3.0.tar.gz'. Unable to fetch URL from any source.
ERROR: velodyne-driver-1.3.0-r0 do_fetch: Function failed: base_do_fetch

**Comment by shr-project** [comment]
See https://github.com/ros/meta-ros/pull/625 which should fix this.

**Comment by herb-kuta-lge** [comment]
@monicuti < Can this issue be closed?

**Comment by monicuti** [comment]
Hello, yes, that fix the issue.
Thanks!
