### ISSUE TITLE
OpenEmbedded warrior support

### ISSUE THREAD

**Issue by manuelvolk** [ros/meta-ros#638]
Hello everyone,
is there already a roadmap when meta-ros should be available for OpenEmbedded warrior? 
Are you already working on it?
What should be done to help?

**Comment by herb-kuta-lge** [comment]
A milestone for initial support of OpenEmbedded **warrior** appears [here](https://github.com/ros/meta-ros/wiki/Superflore-OE-Recipe-Generation-Scheme#milestone-9-initial-support-for-oe-core-warrior), having been added in the recently published revision 41 of _Superflore OE Recipe Generation Scheme_.

**Comment by sprhawk** [comment]
@herb-kuta-lge I got my own support for warrior in [my fork](https://github.com/sprhawk/meta-ros/tree/warrior-draft)
I want to make a pull request but there is no warrior branch for now.

**Comment by herb-kuta-lge** [comment]
Thanks for offering to share your work. We have still not reached the [**warrior** support milestone](https://github.com/ros/meta-ros/wiki/Superflore-OE-Recipe-Generation-Scheme#milestone-9-initial-support-for-oe-core-warrior). Please be patient.

**Comment by shr-project** [comment]
Warrior support available in https://github.com/ros/meta-ros/pull/658.

All changes are backwards compatible, so thud and warrior branches might be identical for a while.

**Comment by shr-project** [comment]
Warrior support was merged with #658. 5 months ago, closing this ticket.
