### ISSUE TITLE
meta-ros purposes

### ISSUE THREAD

**Issue by sancelot** [ros/meta-ros#642]
Hi,
If I understand this repository is dedicated to build ros for openembedded.

I am thinking about a way to build  ROS in a more generic way using cmake to download  needed packages and build them, in order being independt of the platform. 

Is it a good start , from here?

Regards,
S.Ancelot

**Comment by gavanderhoorn** [comment]
Context: [ROS setup with cmake](https://answers.ros.org/question/337420) on ROS Answers.

**Comment by herb-kuta-lge** [comment]
> Is it a good start , from here?

It could be if you are OK with using [**bitbake**](https://www.yoctoproject.org/docs/current/bitbake-user-manual/bitbake-user-manual.html) to download and build the packages instead of **cmake**.

**Comment by herb-kuta-lge** [comment]
@sancelot < Can this issue be closed?

**Comment by sancelot** [comment]
Yes, you can.
