### ISSUE TITLE
Is the rebasing of meta-ros branches causing you grief?

### ISSUE THREAD

**Issue by herb-kuta-lge** [ros/meta-ros#670]
Our current plan is to stop rebasing `[thud-draft]` and `[build-draft]` (and to rename them `[thud]` and `[build]`) as part of [Milestone 13](https://github.com/ros/meta-ros/wiki/Superflore-OE-Recipe-Generation-Scheme#milestone-13-cleanup). However, if rebasing them is causing members of the community to curse us, it would behoove us to do it sooner. What do you think? Please respond by 2019-01-24 00:00 UTC.

**Comment by shr-project** [comment]
Branches without the '-draft' suffix were created and are in sync with the ones with '-draft' suffix. They will be kept in the repository for some transitional period and then deleted with the Milestone 14 changes.
