### ISSUE TITLE
ROS2 recipe for Foxy release

### ISSUE THREAD

**Issue by hyang5** [ros/meta-ros#683]
Is there any plan to support Foxy release?

**Comment by herb-kuta-lge** [comment]
Yes! Our plan is to add support for it in [Milestone 14](https://github.com/ros/meta-ros/wiki/Superflore-OE-Recipe-Generation-Scheme#milestone-14-support-ros-2-foxy).

**Comment by shr-project** [comment]
It was merged just now, please try it and let us know.

**Comment by shr-project** [comment]
I'm going to assume that it works OK for you, please create new issue ticket if you find some issues later.

"Silence implies consent" (see http://wiki.c2.com/?SilenceImpliesConsent).

Today the foxy support was also added to branches for old OE releases thud, warrior and zeus.

**Comment by hyang5** [comment]
> I'm going to assume that it works OK for you, please create new issue ticket if you find some issues later.
> 
> "Silence implies consent" (see http://wiki.c2.com/?SilenceImpliesConsent).
> 
> Today the foxy support was also added to branches for old OE releases thud, warrior and zeus.

Thanks. It works.
