### ISSUE TITLE
meta-ros yocto dunfell support status

### ISSUE THREAD

**Issue by avinashiitk** [ros/meta-ros#689]
I don't see /remotes/origin/dunfell-draft branch with meta-ros. 
Do we have plans to support dunfell (Yocto 3.1) on meta-ros?

**Comment by shr-project** [comment]
Yes, it's already implemented in:
https://github.com/shr-project/meta-ros/tree/dunfell-draft
and .mcf files in:
https://github.com/shr-project/meta-ros/tree/build-draft-ms12

Hopefully it will be merged here soon, there is pull request for master-draft https://github.com/ros/meta-ros/pull/680, when it's merged to master, dunfell branch will be created as well.

**Comment by avinashiitk** [comment]
Thanks for information. Do you have timeline, when dunfell-draft will get merged and branch will get created?
-Avinash

**Comment by shr-project** [comment]
It was merged just now, please try it and let us know.

**Comment by shr-project** [comment]
I'm going to assume that it works OK for you, please create new issue ticket if you find some issues later.

"Silence implies consent" (see http://wiki.c2.com/?SilenceImpliesConsent).
