### ISSUE TITLE
Is meta-ros supporting moveit2 on ROS2 Dashing/ Foxy?

### ISSUE THREAD

**Issue by avinashiitk** [ros/meta-ros#714]
Is meta-ros supporting moveit2 on ROS2 Dashing/ Foxy?
regards
Avinash

**Comment by shr-project** [comment]
Is there a Dashing/Foxy release which supports moveit2? I haven't seen it yet.

meta-ros has recipes generated with superflore from official rosdistro repo, if moveit2 is not yet there, it won't be generated in meta-ros. Latest Foxy release we have prepared is 2020-07-23 in https://github.com/ros/meta-ros/pull/709 which contains e.g. navigation2, but not moveit2.

**Comment by shr-project** [comment]
See https://github.com/ros/meta-ros/pull/757 but it's not ready for merge yet
