### ISSUE TITLE
what is difference between webOSose and webOS + ROS?

### ISSUE THREAD

**Issue by HyunCello** [ros/meta-ros#715]
Hi I am doing project with webOSose, also I want to use ROS in webOS.

Results from my searching, there is no way to using ROS without extra building.

I used ROS for other projects, so I got a question.

Currently, I use external web app to using LS2 api and monitor.
But after the integrate ROS to webOS build, how would I access to ROS in webOS?

It is too confusing to me, because I can't find CLI solution in webOSose..

This is my opinion.

1. webOS + ROS is different from webOSose. so if I turn on RPi4, terminal will shown

2. there is another way to access terminal in webOSose. So people can run ros package or roscore from that

What is Correct? Thank you.

**Comment by shr-project** [comment]
Please reopen if you have additional questions.
