### ISSUE TITLE
meta-ros foxy (shared-queues-vendor) build failure on Yocto dunfill after update to milestone 14

### ISSUE THREAD

**Issue by rafaelhuang-intel** [ros/meta-ros#738]
Sharing build log:
build is for Yocto Dunfell.
Ubuntu 18.04 
Metao-ros updated to milestone 14 (commit: a135ffc)
Issue is faced with foxy. (this issue also meet on openembedded build environment.)

[shared-queues-vendor_U18.04_log.do_compile.27097.txt](https://github.com/ros/meta-ros/files/5222554/shared-queues-vendor_U18.04_log.do_compile.27097.txt)

**Comment by shr-project** [comment]
```
error: downloading 'https://github.com/cameron314/readerwriterqueue/archive/ef7dfbf553288064347d51b8ac335f1ca489032a.zip' failed
         status_code: 28
         status_string: "Timeout was reached"
         log:
         --- LOG BEGIN ---
           Trying 13.229.188.59:443...

  Connection timed out after 60001 milliseconds

  Closing connection 0
```

Looks like network issue, recipes should use bitbake fetcher and we have fixed many of them but there are still some which fetch something during the build and you need to have working network for that.

Are you able to create a patch based on previous fixes I did e.g. in https://github.com/ros/meta-ros/issues/684
