### ISSUE TITLE
turtlesim_1.2.5 not building on meta-ros2-foxy

### ISSUE THREAD

**Issue by munoz0raul** [ros/meta-ros#788]
Hi all, I'm trying to build turtlesim + qt but I had an issue that I couldn't find a solution.

```
CMake Error at CMakeLists.txt:45 (qt5_wrap_cpp):
  Unknown CMake command "qt5_wrap_cpp".
```

I'm using meta-ros2-foxy on gatesgarth. It works fine without turtlesim.

Any idea on how to fix it?

**Comment by shr-project** [comment]
See corresponding fix in dashing:
https://github.com/ros/meta-ros/commit/3faebc2a24d5b3ac5e57d960cbc3ea2a2d652c37

**Comment by munoz0raul** [comment]
Hello @shr-project, I manage fix the issue with this bbappend:

```
inherit cmake qmake5_paths
inherit populate_sdk_qt5

EXTRA_OECMAKE = "-DOE_QMAKE_PATH_EXTERNAL_HOST_BINS='${OE_QMAKE_PATH_EXTERNAL_HOST_BINS}'"

ROS_BUILDTOOL_EXPORT_DEPENDS_prepend = " \
    ament-cmake-native \
    rosidl-cmake-native \
"

DEPENDS += "qtbase qtbase-native rosidl-typesupport-fastrtps-cpp-native rosidl-typesupport-fastrtps-c-native"
```


After qt errors, I also got some missing dependencies relates to fastrtps-c and cpp.

With my changes I tested and it works fine.

![image](https://user-images.githubusercontent.com/7702208/105222905-de8d5580-5b39-11eb-8b67-e9fab01a2d67.png)
