### ISSUE TITLE
Rviz can't be build in meta-ros1-melodic

### ISSUE THREAD

**Issue by minhthuc2502** [ros/meta-ros#799]
Hello,

I'm trying to use meta-ros on `branch zeus` for my card which run only version zeus of yocto. i used steps in [wiki].(https://github.com/ros/meta-ros/wiki/OpenEmbedded-Build-Instructions#add-meta-ros-to-an-existing-openembedded-project)

I want to run the simulation rviz on this card so i tried to use recipe `rviz` by `bitbake rviz`. The problem is that rviz uses Qt5 and it can't find the path for header files of Qt. As i checked, the directory of qt is installed correctly in `recipe-sysroot`. 

![Screenshot from 2021-02-17 14-28-09](https://user-images.githubusercontent.com/46375464/108328176-957a0100-71cc-11eb-932f-18b73821c434.png)

Before, I have some errors like missing `sip binding generator`, then i added `sip sip-native and python-sip` for rviz and let `PNBLACKLIST[rviz]` empty to unblacklist rviz.

What is the configuration I missed?

Any help would be greatly appreciated!

**Comment by ABTrac** [comment]
Hi @minhthuc2502 and community 

I am running into a similar problem . I have added meta-ros to an existing image as instructed in [https://github.com/ros/meta-ros/wiki/OpenEmbedded-Build-Instructions#add-meta-ros-to-an-existing-openembedded-project](url) and everything was successfully compiled. However, when I wanted to add Rviz to the image I got the following configuration errors:

![Screenshot from 2022-04-14 11-33-53](https://user-images.githubusercontent.com/82082166/163347509-bb170990-0d25-43c9-83c6-51723c9717b1.png)

I am building the image from the Dunfell branch, and I have added `meta-qt5` layer and also added sip in local.conf  `IMAGE_INSTALL_append= " sip"` and removed rviz from the blacklist.  @minhthuc2502 I would really appreciate if you can please elaborate what you did to fix the  `SIP binding generator NOT available ` error. Thank you very much :)

**Comment by robwoolley** [comment]
Closing as Melodic is no longer supported.
