### ISSUE TITLE
ROS2 with Toradex Build a Reference Image with Yocto Project

### ISSUE THREAD

**Issue by ierturk** [ros/meta-ros#811]
Hi,

I'm newbie to build yocto, I followed the guid for `Build a Reference Image with Yocto Project` [1], I was succeeded. However, when I added `ROS2` layer into `bblayers.conf `as follow as described here[2] I got the error message below.

```
 ...
 ${TOPDIR}/../layers/openembedded-core/meta \
 ${TOPDIR}/../../extra/meta-ros/meta-ros2-foxy \
 ...
```
the error message
```
 bitbake tdx-reference-minimal-image
 ERROR: Unable to start bitbake server (None)
 ERROR: Server log for this session (/media/ierturk/Work/REPOs/toradex/yocto/oe_core/build/bitbake-cookerdaemon.log):
 --- Starting bitbake server pid 2720 at 2021-03-24 14:50:17.098520 ---
 ERROR: Layer ros2-foxy-layer is not compatible with the core layer which only supports these series: dunfell (layer is compatible with ${ROS_OE_RELEASE_SERIES})
```

Environment:

    * Ubuntu 20.04 - 64 bit
    * Target Board: Toradex Verdin Mini

Thanks in advance...

Ibrahim

[1] https://developer.toradex.com/knowledge-base/board-support-package/openembedded-core
[2] https://github.com/ros/meta-ros/wiki/OpenEmbedded-Build-Instructions#add-meta-ros-to-an-existing-openembedded-project

**Comment by shr-project** [comment]
What meta-ros revision are you using? You're definitely missing bunch of layer dependencies like meta-ros-common (which sets ROS_OE_RELEASE_SERIES and also e.g. meta-ros2, meta-oe, meta-python etc)

**Comment by ierturk** [comment]
Hi @shr-project,

It seems to be OK when following line added into `bblayers.conf` as you suggested.
```
  ${TOPDIR}/../../extra/meta-ros/meta-ros-common \
  ${TOPDIR}/../../extra/meta-ros/meta-ros-backports-gatesgarth \
  ${TOPDIR}/../../extra/meta-ros/meta-ros2 \
  ${TOPDIR}/../../extra/meta-ros/meta-ros2-foxy \
```
Thanks for your the reply. You saved my day. Building started successfully. Once the image will be created, I'll check it then let you know.

**Comment by ierturk** [comment]
Hi @shr-project thanhs again. Everything is OK with the image ROS2 Foxy and Torizon Yocto Verdin.

**Comment by jg-spitfire** [comment]
Hi @ierturk, I undertsand that you only had to follow [these](https://github.com/ros/meta-ros/wiki/OpenEmbedded-Build-Instructions#add-meta-ros-to-an-existing-openembedded-project) steps right?

Add meta-ros to an Existing OpenEmbedded Project

    1.Clone the branch of ros/meta-ros.git for the OpenEmbedded release series you are using.

    2.Add meta-ros[12]-<ROS_DISTRO> to your conf/bblayers.conf.

    3.Run bitbake -p ros-core.

    4.Add the other layers it reports as missing to your conf/bblayers.conf.

    5.Add whatever might be useful from step 3 of the previous section to the bottom of your conf/local.conf.

did you do this while running your running Torizon Yocto Verdin or you had to follow those steps then build the image and flash your sd?, sorry but I am newbie in this
