### ISSUE TITLE
aws-c-event-stream source missing

### ISSUE THREAD

**Issue by alan-gu** [ros/meta-ros#864]
**Describe the bug**
I'm trying to build ros1 melodic cross compiling env on x86, by following this page [https://github.com/ros/meta-ros/wiki/OpenEmbedded-Build-Instructions](https://github.com/ros/meta-ros/wiki/OpenEmbedded-Build-Instructions).
I met the bug at this step

> 2. ros-image-world
>This image contains all packages from a ROS distro that can be built and included in an image without conflicts.

>source openembedded-core/oe-init-build-env
>cd -
>**bitbake ros-image-world**
aws-c-event-stream cannot be downloaded because the source doesn't exist.

**To Reproduce**
Not sure about Yocto layers. I don't know about Yocto.
My settings are:
distro=ros1
ros_distro=melodic
oe_release_series=hardknott

The "Build Configuration:" section shown by bitbake at the beginning of the build is very good start.

Build Configuration:
BB_VERSION           = "1.50.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "ubuntu-18.04"
TARGET_SYS           = "i686-oe-linux"
MACHINE              = "qemux86"
DISTRO               = "ros1"
DISTRO_VERSION       = "1.melodic.2021-05-17.24-15+3.3-152-hardknott"
TUNE_FEATURES        = "m32 core2"
TARGET_FPU           = ""
DISTRO_NAME          = "Robot Operating System (ROS 1) with OpenEmbedded Linux"
ROS_DISTRO           = "melodic"
ROS_VERSION          = "1"
ROS_PYTHON_VERSION   = "2"
meta-raspberrypi     = "hardknott:11209a4981f03db9988de84752da0076ff6b8f17"
meta-ros1-melodic
meta-ros1
meta-ros-common
meta-ros-python2     = "hardknott:c846e3a3b32bdf83faf5d00eb87c5436ca913cf7"
meta-python2         = "master:810d6d842f103eb59f18b06426106462b15de7e2"
meta-python
meta-oe              = "hardknott:9ee0e08ba2395b9cb93f2273bb1018adb3630407"
meta                 = "hardknott:4a70af7b89d2ddff341b724a97cb96987874a3b0"

**Expected behavior**
no error

error message:

DEBUG: Fetching http://sources.openembedded.org/git2_github.com.awslabs.aws-c-event-stream.git.tar.gz using command '/usr/bin/env wget -t 2 -T 30 --passive-ftp --no-check-certificate -P /work/openebd-build/downloads 'http://sources.openembedded.org/git2_github.com.awslabs.aws-c-event-stream.git.tar.gz''
DEBUG: Fetcher accessed the network with the command /usr/bin/env wget -t 2 -T 30 --passive-ftp --no-check-certificate -P /work/openebd-build/downloads 'http://sources.openembedded.org/git2_github.com.awslabs.aws-c-event-stream.git.tar.gz'
DEBUG: Running export PSEUDO_DISABLED=1; export https_proxy="192.168.110.55:20172"; export PATH="/work/new/openembedded-core/scripts:/work/new/tmp/work/core2-32-oe-linux/aws-c-event-stream/0.1.4-r0/recipe-sysroot-native/usr/bin/i686-oe-linux:/work/new/tmp/work/core2-32-oe-linux/aws-c-event-stream/0.1.4-r0/recipe-sysroot/usr/bin/crossscripts:/work/new/tmp/work/core2-32-oe-linux/aws-c-event-stream/0.1.4-r0/recipe-sysroot-native/usr/sbin:/work/new/tmp/work/core2-32-oe-linux/aws-c-event-stream/0.1.4-r0/recipe-sysroot-native/usr/bin:/work/new/tmp/work/core2-32-oe-linux/aws-c-event-stream/0.1.4-r0/recipe-sysroot-native/sbin:/work/new/tmp/work/core2-32-oe-linux/aws-c-event-stream/0.1.4-r0/recipe-sysroot-native/bin:/work/new/bitbake/bin:/work/new/tmp/hosttools"; export HOME="/work"; /usr/bin/env wget -t 2 -T 30 --passive-ftp --no-check-certificate -P /work/openebd-build/downloads 'http://sources.openembedded.org/git2_github.com.awslabs.aws-c-event-stream.git.tar.gz' --progress=dot -v
--2021-06-10 08:09:40--  http://sources.openembedded.org/git2_github.com.awslabs.aws-c-event-stream.git.tar.gz
Resolving sources.openembedded.org (sources.openembedded.org)... 198.145.29.27
Connecting to sources.openembedded.org (sources.openembedded.org)|198.145.29.27|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-06-10 08:09:42 ERROR 404: Not Found.

DEBUG: Mirror fetch failure for url http://sources.openembedded.org/git2_github.com.awslabs.aws-c-event-stream.git.tar.gz (original url: git://github.com/awslabs/aws-c-event-stream.git;protocol=https)
DEBUG: Fetcher failure: Fetch command export PSEUDO_DISABLED=1; export https_proxy="192.168.110.55:20172"; export PATH="/work/new/openembedded-core/scripts:/work/new/tmp/work/core2-32-oe-linux/aws-c-event-stream/0.1.4-r0/recipe-sysroot-native/usr/bin/i686-oe-linux:/work/new/tmp/work/core2-32-oe-linux/aws-c-event-stream/0.1.4-r0/recipe-sysroot/usr/bin/crossscripts:/work/new/tmp/work/core2-32-oe-linux/aws-c-event-stream/0.1.4-r0/recipe-sysroot-native/usr/sbin:/work/new/tmp/work/core2-32-oe-linux/aws-c-event-stream/0.1.4-r0/recipe-sysroot-native/usr/bin:/work/new/tmp/work/core2-32-oe-linux/aws-c-event-stream/0.1.4-r0/recipe-sysroot-native/sbin:/work/new/tmp/work/core2-32-oe-linux/aws-c-event-stream/0.1.4-r0/recipe-sysroot-native/bin:/work/new/bitbake/bin:/work/new/tmp/hosttools"; export HOME="/work"; /usr/bin/env wget -t 2 -T 30 --passive-ftp --no-check-certificate -P /work/openebd-build/downloads 'http://sources.openembedded.org/git2_github.com.awslabs.aws-c-event-stream.git.tar.gz' --progress=dot -v failed with exit code 8, output:
--2021-06-10 08:09:40--  http://sources.openembedded.org/git2_github.com.awslabs.aws-c-event-stream.git.tar.gz
Resolving sources.openembedded.org (sources.openembedded.org)... 198.145.29.27
Connecting to sources.openembedded.org (sources.openembedded.org)|198.145.29.27|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-06-10 08:09:42 ERROR 404: Not Found.

ERROR: Fetcher failure: Unable to find revision 32713d30b479690d199b3f02163a832b09b309a5 in branch master even from upstream
ERROR: Fetcher failure for URL: 'git://github.com/awslabs/aws-c-event-stream.git;protocol=https'. Unable to fetch URL from any source.
DEBUG: Python function base_do_fetch finished
DEBUG: Python function do_fetch finished

I checked http://sources.openembedded.org/, there is no git2_github.com.awslabs.aws-c-event-stream.git.tar.gz.
I also cloned git://github.com/awslabs/aws-c-event-stream.git, 32713d30b479690d199b3f02163a832b09b309a5 does exist.

**Comment by shr-project** [comment]
Probably needs the same fix as other aws recipes in:
https://github.com/ros/meta-ros/commit/7321bdbba9e0485484d92ef7e3ca08c874fc0a88
