### ISSUE TITLE
How to downgrade the yocto version with meta-ros

### ISSUE THREAD

**Issue by Justin790126** [ros/meta-ros#867]
Here I have to use yocto 3.1.0 to build meta-ros1-melodic for some usage.

What files should I need to edit to fetch the correspond yocto version with your SOP in instruction ?

**Comment by shr-project** [comment]
What you mean? You cannot use newer dunfell branch revision than the initial 3.1.0? Why? 3.1.0 is missing many important changes and fixes.

**Comment by Justin790126** [comment]
Because my hardware i500’s newest yocto version is yocto3.1.0. I have no choice but to use this version to build meta-ros.

**Comment by shr-project** [comment]
Sorry, I don't know what i500 is (https://layers.openembedded.org/layerindex/branch/master/machines/?q=i500&search=1 doesn't show anything as well) or why it would be incompatible with 3.1.10 (latest revision of dunfell release as in https://lists.yoctoproject.org/g/poky/message/12511).

**Comment by robwoolley** [comment]
This doesn't appear to be a bug and is over 2 years old.
