### ISSUE TITLE
oe layer index is missing noetic

### ISSUE THREAD

**Issue by kranzo** [ros/meta-ros#899]
http://layers.openembedded.org/ is missing meta-ros1-noetic?

Is there a reason for this? Could i fix this or who can add the layer? 
I indend to use ` bitbake-layers layerindex-fetch` as layer dependecy resolver and like to use in for melodic and noetic.

**Comment by shr-project** [comment]
Thanks for report, I'll add noetic and galactic there.

**Comment by shr-project** [comment]
http://layers.openembedded.org/layerindex/branch/master/layer/meta-ros1-noetic/
http://layers.openembedded.org/layerindex/branch/master/layer/meta-ros2-galactic/
