### ISSUE TITLE
bitbake ros-core / ros-image-core gives "rcutils" error (files installed but not shipped)

### ISSUE THREAD

**Issue by suyash-narain** [ros/meta-ros#917]
I am trying to create a ros2 image for ros2-rolling hardknott, for aarch64 armv8 architecture. Creating the standalone image for qemux86-64 works, but when i try to add meta-ros layer to existing openembedded layers (poky and meta-openembedded), bitbake ros-core or for the matter, any of the ros recipes does not seem to work.

The following three tasks always fail:
Summary: 3 tasks failed:
  /home1/usrdir/mtk23610/rity_images/hardknott_ros/src/poky/../meta-ros/meta-ros2-rolling/generated-recipes/rosidl/rosidl-runtime-c_2.5.0-1.bb:do_configure
  /home1/usrdir/mtk23610/rity_images/hardknott_ros/src/poky/../meta-ros/meta-ros2-rolling/generated-recipes/rcpputils/rcpputils_2.2.0-1.bb:do_configure
  /home1/usrdir/mtk23610/rity_images/hardknott_ros/src/poky/../meta-ros/meta-ros2-rolling/generated-recipes/rcutils/rcutils_4.0.2-1.bb:do_package

the entire error log is as follows:
########################################################################
Initialising tasks: 100% |################################################################################################################################################################################| Time: 0:00:04
Sstate summary: Wanted 748 Local 7 Network 0 Missed 741 Current 754 (0% match, 50% complete)
NOTE: Executing Tasks
ERROR: rosidl-runtime-c-2.5.0-1-r0 do_configure: Execution of '/home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rosidl-runtime-c/2.5.0-1-r0/temp/run.do_configure.7232' failed with exit code 1:
-- The C compiler identification is GNU 10.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rosidl-runtime-c/2.5.0-1-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux/aarch64-poky-linux-gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Found ament_cmake_ros: 0.9.2 (/home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rosidl-runtime-c/2.5.0-1-r0/recipe-sysroot-native/usr/share/ament_cmake_ros/cmake)
-- Found PythonInterp: /home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rosidl-runtime-c/2.5.0-1-r0/recipe-sysroot-native/usr/bin/python3-native/python3 (found suitable version "3.9.5", minimum required is "3") 
-- Using PYTHON_EXECUTABLE: /home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rosidl-runtime-c/2.5.0-1-r0/recipe-sysroot-native/usr/bin/python3-native/python3
-- Found rcutils: 4.0.2 (/home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rosidl-runtime-c/2.5.0-1-r0/recipe-sysroot/usr/share/rcutils/cmake)
CMake Error at /home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rosidl-runtime-c/2.5.0-1-r0/recipe-sysroot/usr/share/rcutils/cmake/ament_cmake_export_libraries-extras.cmake:48 (message):
  Package 'rcutils' exports the library 'rcutils' which couldn't be found
Call Stack (most recent call first):
  /home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rosidl-runtime-c/2.5.0-1-r0/recipe-sysroot/usr/share/rcutils/cmake/rcutilsConfig.cmake:41 (include)
  CMakeLists.txt:15 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rosidl-runtime-c/2.5.0-1-r0/build/CMakeFiles/CMakeOutput.log".
WARNING: exit code 1 from a shell command.

ERROR: Logfile of failure stored in: /home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rosidl-runtime-c/2.5.0-1-r0/temp/log.do_configure.7232
Log data follows:
| DEBUG: Executing python function extend_recipe_sysroot
| NOTE: Direct dependencies are ['/home1/usrdir/mtk23610/rity_images/hardknott_ros/src/poky/../meta-ros/meta-ros2-rolling/generated-recipes/rosidl/rosidl-typesupport-interface_2.5.0-1.bb:do_populate_sysroot', 'virtual:native:/home1/usrdir/mtk23610/rity_images/hardknott_ros/src/poky/meta/recipes-devtools/patch/patch_2.7.6.bb:do_populate_sysroot', '/home1/usrdir/mtk23610/rity_images/hardknott_ros/src/poky/meta/recipes-core/glibc/glibc_2.33.bb:do_populate_sysroot', '/home1/usrdir/mtk23610/rity_images/hardknott_ros/src/poky/meta/recipes-devtools/quilt/quilt-native_0.66.bb:do_populate_sysroot', 'virtual:native:/home1/usrdir/mtk23610/rity_images/hardknott_ros/src/poky/meta/recipes-devtools/python/python3_3.9.5.bb:do_populate_sysroot', '/home1/usrdir/mtk23610/rity_images/hardknott_ros/src/poky/meta/recipes-devtools/gcc/gcc-cross_10.2.bb:do_populate_sysroot', 'virtual:native:/home1/usrdir/mtk23610/rity_images/hardknott_ros/src/poky/meta/recipes-devtools/ninja/ninja_1.10.2.bb:do_populate_sysroot', 'virtual:native:/home1/usrdir/mtk23610/rity_images/hardknott_ros/src/poky/../meta-ros/meta-ros2-rolling/generated-recipes/ament-cmake-ros/ament-cmake-ros_0.9.2-1.bb:do_populate_sysroot', '/home1/usrdir/mtk23610/rity_images/hardknott_ros/src/poky/../meta-ros/meta-ros2-rolling/generated-recipes/rcutils/rcutils_4.0.2-1.bb:do_populate_sysroot', '/home1/usrdir/mtk23610/rity_images/hardknott_ros/src/poky/meta/recipes-devtools/gcc/gcc-runtime_10.2.bb:do_populate_sysroot', '/home1/usrdir/mtk23610/rity_images/hardknott_ros/src/poky/meta/recipes-devtools/cmake/cmake-native_3.19.5.bb:do_populate_sysroot', 'virtual:native:/home1/usrdir/mtk23610/rity_images/hardknott_ros/src/poky/meta/recipes-devtools/pseudo/pseudo_git.bb:do_populate_sysroot', 'virtual:native:/home1/usrdir/mtk23610/rity_images/hardknott_ros/src/poky/../meta-ros/meta-ros2-rolling/generated-recipes/ament-cmake/ament-cmake_1.1.4-1.bb:do_populate_sysroot']
| NOTE: Installed into sysroot: []
| NOTE: Skipping as already exists in sysroot: ['rosidl-typesupport-interface', 'patch-native', 'glibc', 'quilt-native', 'python3-native', 'gcc-cross-aarch64', 'ninja-native', 'ament-cmake-ros-native', 'rcutils', 'gcc-runtime', 'cmake-native', 'pseudo-native', 'ament-cmake-native', 'autoconf-native', 'libtool-native', 'automake-native', 'attr-native', 'linux-libc-headers', 'gdbm-native', 'util-linux-native', 'readline-native', 'zlib-native', 'xz-native', 'libffi-native', 'sqlite3-native', 'openssl-native', 'libtirpc-native', 'pkgconfig-native', 'libnsl2-native', 'bzip2-native', 're2c-native', 'ament-cmake-gtest-native', 'ament-cmake-gmock-native', 'domain-coordinator-native', 'ament-cmake-pytest-native', 'ncurses-native', 'curl-native', 'ament-cmake-export-libraries-native', 'ament-cmake-test-native', 'ament-cmake-export-interfaces-native', 'ament-cmake-target-dependencies-native', 'ament-cmake-export-targets-native', 'ament-cmake-libraries-native', 'ament-cmake-version-native', 'ament-cmake-core-native', 'ament-cmake-python-native', 'ament-cmake-export-include-directories-native', 'ament-cmake-export-link-flags-native', 'ament-cmake-export-dependencies-native', 'ament-cmake-export-definitions-native', 'gmp-native', 'binutils-cross-aarch64', 'libmpc-native', 'mpfr-native', 'flex-native', 'gnu-config-native', 'texinfo-dummy-native', 'libgcc', 'm4-native', 'gettext-minimal-native', 'util-linux-libuuid-native', 'libcap-ng-native', 'libpcre2-native', 'googletest-native', 'gtest-vendor-native', 'gmock-vendor-native', 'python3-setuptools-native', 'python3-pytest-native', 'ament-cmake-include-directories-native', 'ament-package-native', 'python3-catkin-pkg-native', 'python3-importlib-metadata-native', 'python3-pyparsing-native', 'python3-setuptools-scm-native', 'python3-toml-native', 'python3-zipp-native', 'python3-pathlib2-native', 'python3-more-itertools-native', 'python3-six-native']
| DEBUG: Python function extend_recipe_sysroot finished
| DEBUG: Executing shell function do_configure
| -- The C compiler identification is GNU 10.2.0
| -- Detecting C compiler ABI info
| -- Detecting C compiler ABI info - done
| -- Check for working C compiler: /home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rosidl-runtime-c/2.5.0-1-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux/aarch64-poky-linux-gcc - skipped
| -- Detecting C compile features
| -- Detecting C compile features - done
| -- Found ament_cmake_ros: 0.9.2 (/home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rosidl-runtime-c/2.5.0-1-r0/recipe-sysroot-native/usr/share/ament_cmake_ros/cmake)
| -- Found PythonInterp: /home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rosidl-runtime-c/2.5.0-1-r0/recipe-sysroot-native/usr/bin/python3-native/python3 (found suitable version "3.9.5", minimum required is "3")
| -- Using PYTHON_EXECUTABLE: /home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rosidl-runtime-c/2.5.0-1-r0/recipe-sysroot-native/usr/bin/python3-native/python3
| -- Found rcutils: 4.0.2 (/home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rosidl-runtime-c/2.5.0-1-r0/recipe-sysroot/usr/share/rcutils/cmake)
| CMake Error at /home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rosidl-runtime-c/2.5.0-1-r0/recipe-sysroot/usr/share/rcutils/cmake/ament_cmake_export_libraries-extras.cmake:48 (message):
|   Package 'rcutils' exports the library 'rcutils' which couldn't be found
| Call Stack (most recent call first):
|   /home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rosidl-runtime-c/2.5.0-1-r0/recipe-sysroot/usr/share/rcutils/cmake/rcutilsConfig.cmake:41 (include)
|   CMakeLists.txt:15 (find_package)
| 
| 
| -- Configuring incomplete, errors occurred!
| See also "/home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rosidl-runtime-c/2.5.0-1-r0/build/CMakeFiles/CMakeOutput.log".
| WARNING: exit code 1 from a shell command.
| ERROR: Execution of '/home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rosidl-runtime-c/2.5.0-1-r0/temp/run.do_configure.7232' failed with exit code 1:
| -- The C compiler identification is GNU 10.2.0
| -- Detecting C compiler ABI info
| -- Detecting C compiler ABI info - done
| -- Check for working C compiler: /home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rosidl-runtime-c/2.5.0-1-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux/aarch64-poky-linux-gcc - skipped
| -- Detecting C compile features
| -- Detecting C compile features - done
| -- Found ament_cmake_ros: 0.9.2 (/home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rosidl-runtime-c/2.5.0-1-r0/recipe-sysroot-native/usr/share/ament_cmake_ros/cmake)
| -- Found PythonInterp: /home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rosidl-runtime-c/2.5.0-1-r0/recipe-sysroot-native/usr/bin/python3-native/python3 (found suitable version "3.9.5", minimum required is "3")
| -- Using PYTHON_EXECUTABLE: /home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rosidl-runtime-c/2.5.0-1-r0/recipe-sysroot-native/usr/bin/python3-native/python3
| -- Found rcutils: 4.0.2 (/home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rosidl-runtime-c/2.5.0-1-r0/recipe-sysroot/usr/share/rcutils/cmake)
| CMake Error at /home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rosidl-runtime-c/2.5.0-1-r0/recipe-sysroot/usr/share/rcutils/cmake/ament_cmake_export_libraries-extras.cmake:48 (message):
|   Package 'rcutils' exports the library 'rcutils' which couldn't be found
| Call Stack (most recent call first):
|   /home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rosidl-runtime-c/2.5.0-1-r0/recipe-sysroot/usr/share/rcutils/cmake/rcutilsConfig.cmake:41 (include)
|   CMakeLists.txt:15 (find_package)
| 
| 
| -- Configuring incomplete, errors occurred!
| See also "/home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rosidl-runtime-c/2.5.0-1-r0/build/CMakeFiles/CMakeOutput.log".
| WARNING: exit code 1 from a shell command.
| 
ERROR: Task (/home1/usrdir/mtk23610/rity_images/hardknott_ros/src/poky/../meta-ros/meta-ros2-rolling/generated-recipes/rosidl/rosidl-runtime-c_2.5.0-1.bb:do_configure) failed with exit code '1'
ERROR: rcpputils-2.2.0-1-r0 do_configure: Execution of '/home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rcpputils/2.2.0-1-r0/temp/run.do_configure.7986' failed with exit code 1:
-- The C compiler identification is GNU 10.2.0
-- The CXX compiler identification is GNU 10.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rcpputils/2.2.0-1-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux/aarch64-poky-linux-gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rcpputils/2.2.0-1-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux/aarch64-poky-linux-g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found ament_cmake: 1.1.4 (/home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rcpputils/2.2.0-1-r0/recipe-sysroot-native/usr/share/ament_cmake/cmake)
-- Found PythonInterp: /home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rcpputils/2.2.0-1-r0/recipe-sysroot-native/usr/bin/python3-native/python3 (found suitable version "3.9.5", minimum required is "3") 
-- Using PYTHON_EXECUTABLE: /home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rcpputils/2.2.0-1-r0/recipe-sysroot-native/usr/bin/python3-native/python3
-- Found ament_cmake_ros: 0.9.2 (/home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rcpputils/2.2.0-1-r0/recipe-sysroot-native/usr/share/ament_cmake_ros/cmake)
-- Found rcutils: 4.0.2 (/home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rcpputils/2.2.0-1-r0/recipe-sysroot/usr/share/rcutils/cmake)
CMake Error at /home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rcpputils/2.2.0-1-r0/recipe-sysroot/usr/share/rcutils/cmake/ament_cmake_export_libraries-extras.cmake:48 (message):
  Package 'rcutils' exports the library 'rcutils' which couldn't be found
Call Stack (most recent call first):
  /home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rcpputils/2.2.0-1-r0/recipe-sysroot/usr/share/rcutils/cmake/rcutilsConfig.cmake:41 (include)
  CMakeLists.txt:7 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rcpputils/2.2.0-1-r0/build/CMakeFiles/CMakeOutput.log".
WARNING: exit code 1 from a shell command.

ERROR: Logfile of failure stored in: /home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rcpputils/2.2.0-1-r0/temp/log.do_configure.7986
Log data follows:
| DEBUG: Executing python function extend_recipe_sysroot
| NOTE: Direct dependencies are ['virtual:native:/home1/usrdir/mtk23610/rity_images/hardknott_ros/src/poky/meta/recipes-devtools/patch/patch_2.7.6.bb:do_populate_sysroot', '/home1/usrdir/mtk23610/rity_images/hardknott_ros/src/poky/meta/recipes-core/glibc/glibc_2.33.bb:do_populate_sysroot', '/home1/usrdir/mtk23610/rity_images/hardknott_ros/src/poky/meta/recipes-devtools/quilt/quilt-native_0.66.bb:do_populate_sysroot', 'virtual:native:/home1/usrdir/mtk23610/rity_images/hardknott_ros/src/poky/meta/recipes-devtools/python/python3_3.9.5.bb:do_populate_sysroot', '/home1/usrdir/mtk23610/rity_images/hardknott_ros/src/poky/meta/recipes-devtools/gcc/gcc-cross_10.2.bb:do_populate_sysroot', 'virtual:native:/home1/usrdir/mtk23610/rity_images/hardknott_ros/src/poky/../meta-ros/meta-ros2-rolling/generated-recipes/ament-cmake-ros/ament-cmake-ros_0.9.2-1.bb:do_populate_sysroot', 'virtual:native:/home1/usrdir/mtk23610/rity_images/hardknott_ros/src/poky/meta/recipes-devtools/ninja/ninja_1.10.2.bb:do_populate_sysroot', '/home1/usrdir/mtk23610/rity_images/hardknott_ros/src/poky/../meta-ros/meta-ros2-rolling/generated-recipes/rcutils/rcutils_4.0.2-1.bb:do_populate_sysroot', '/home1/usrdir/mtk23610/rity_images/hardknott_ros/src/poky/meta/recipes-devtools/gcc/gcc-runtime_10.2.bb:do_populate_sysroot', '/home1/usrdir/mtk23610/rity_images/hardknott_ros/src/poky/meta/recipes-devtools/cmake/cmake-native_3.19.5.bb:do_populate_sysroot', 'virtual:native:/home1/usrdir/mtk23610/rity_images/hardknott_ros/src/poky/meta/recipes-devtools/pseudo/pseudo_git.bb:do_populate_sysroot', 'virtual:native:/home1/usrdir/mtk23610/rity_images/hardknott_ros/src/poky/../meta-ros/meta-ros2-rolling/generated-recipes/ament-cmake/ament-cmake_1.1.4-1.bb:do_populate_sysroot']
| NOTE: Installed into sysroot: []
| NOTE: Skipping as already exists in sysroot: ['patch-native', 'glibc', 'quilt-native', 'python3-native', 'gcc-cross-aarch64', 'ament-cmake-ros-native', 'ninja-native', 'rcutils', 'gcc-runtime', 'cmake-native', 'pseudo-native', 'ament-cmake-native', 'autoconf-native', 'libtool-native', 'automake-native', 'attr-native', 'linux-libc-headers', 'gdbm-native', 'util-linux-native', 'readline-native', 'zlib-native', 'xz-native', 'libffi-native', 'sqlite3-native', 'openssl-native', 'libtirpc-native', 'pkgconfig-native', 'libnsl2-native', 'bzip2-native', 'gmp-native', 'binutils-cross-aarch64', 'libmpc-native', 'mpfr-native', 'flex-native', 'gnu-config-native', 'texinfo-dummy-native', 'ament-cmake-gtest-native', 'ament-cmake-gmock-native', 'domain-coordinator-native', 'ament-cmake-pytest-native', 're2c-native', 'libgcc', 'ncurses-native', 'curl-native', 'ament-cmake-export-libraries-native', 'ament-cmake-test-native', 'ament-cmake-export-interfaces-native', 'ament-cmake-target-dependencies-native', 'ament-cmake-export-targets-native', 'ament-cmake-libraries-native', 'ament-cmake-version-native', 'ament-cmake-core-native', 'ament-cmake-python-native', 'ament-cmake-export-include-directories-native', 'ament-cmake-export-link-flags-native', 'ament-cmake-export-dependencies-native', 'ament-cmake-export-definitions-native', 'm4-native', 'gettext-minimal-native', 'util-linux-libuuid-native', 'libcap-ng-native', 'libpcre2-native', 'googletest-native', 'gtest-vendor-native', 'gmock-vendor-native', 'python3-setuptools-native', 'python3-pytest-native', 'ament-cmake-include-directories-native', 'ament-package-native', 'python3-catkin-pkg-native', 'python3-importlib-metadata-native', 'python3-pyparsing-native', 'python3-setuptools-scm-native', 'python3-toml-native', 'python3-zipp-native', 'python3-pathlib2-native', 'python3-more-itertools-native', 'python3-six-native']
| DEBUG: Python function extend_recipe_sysroot finished
| DEBUG: Executing shell function do_configure
| -- The C compiler identification is GNU 10.2.0
| -- The CXX compiler identification is GNU 10.2.0
| -- Detecting C compiler ABI info
| -- Detecting C compiler ABI info - done
| -- Check for working C compiler: /home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rcpputils/2.2.0-1-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux/aarch64-poky-linux-gcc - skipped
| -- Detecting C compile features
| -- Detecting C compile features - done
| -- Detecting CXX compiler ABI info
| -- Detecting CXX compiler ABI info - done
| -- Check for working CXX compiler: /home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rcpputils/2.2.0-1-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux/aarch64-poky-linux-g++ - skipped
| -- Detecting CXX compile features
| -- Detecting CXX compile features - done
| -- Found ament_cmake: 1.1.4 (/home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rcpputils/2.2.0-1-r0/recipe-sysroot-native/usr/share/ament_cmake/cmake)
| -- Found PythonInterp: /home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rcpputils/2.2.0-1-r0/recipe-sysroot-native/usr/bin/python3-native/python3 (found suitable version "3.9.5", minimum required is "3")
| -- Using PYTHON_EXECUTABLE: /home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rcpputils/2.2.0-1-r0/recipe-sysroot-native/usr/bin/python3-native/python3
| -- Found ament_cmake_ros: 0.9.2 (/home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rcpputils/2.2.0-1-r0/recipe-sysroot-native/usr/share/ament_cmake_ros/cmake)
| -- Found rcutils: 4.0.2 (/home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rcpputils/2.2.0-1-r0/recipe-sysroot/usr/share/rcutils/cmake)
| CMake Error at /home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rcpputils/2.2.0-1-r0/recipe-sysroot/usr/share/rcutils/cmake/ament_cmake_export_libraries-extras.cmake:48 (message):
|   Package 'rcutils' exports the library 'rcutils' which couldn't be found
| Call Stack (most recent call first):
|   /home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rcpputils/2.2.0-1-r0/recipe-sysroot/usr/share/rcutils/cmake/rcutilsConfig.cmake:41 (include)
|   CMakeLists.txt:7 (find_package)
| 
| 
| -- Configuring incomplete, errors occurred!
| See also "/home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rcpputils/2.2.0-1-r0/build/CMakeFiles/CMakeOutput.log".
| WARNING: exit code 1 from a shell command.
| ERROR: Execution of '/home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rcpputils/2.2.0-1-r0/temp/run.do_configure.7986' failed with exit code 1:
| -- The C compiler identification is GNU 10.2.0
| -- The CXX compiler identification is GNU 10.2.0
| -- Detecting C compiler ABI info
| -- Detecting C compiler ABI info - done
| -- Check for working C compiler: /home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rcpputils/2.2.0-1-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux/aarch64-poky-linux-gcc - skipped
| -- Detecting C compile features
| -- Detecting C compile features - done
| -- Detecting CXX compiler ABI info
| -- Detecting CXX compiler ABI info - done
| -- Check for working CXX compiler: /home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rcpputils/2.2.0-1-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux/aarch64-poky-linux-g++ - skipped
| -- Detecting CXX compile features
| -- Detecting CXX compile features - done
| -- Found ament_cmake: 1.1.4 (/home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rcpputils/2.2.0-1-r0/recipe-sysroot-native/usr/share/ament_cmake/cmake)
| -- Found PythonInterp: /home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rcpputils/2.2.0-1-r0/recipe-sysroot-native/usr/bin/python3-native/python3 (found suitable version "3.9.5", minimum required is "3")
| -- Using PYTHON_EXECUTABLE: /home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rcpputils/2.2.0-1-r0/recipe-sysroot-native/usr/bin/python3-native/python3
| -- Found ament_cmake_ros: 0.9.2 (/home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rcpputils/2.2.0-1-r0/recipe-sysroot-native/usr/share/ament_cmake_ros/cmake)
| -- Found rcutils: 4.0.2 (/home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rcpputils/2.2.0-1-r0/recipe-sysroot/usr/share/rcutils/cmake)
| CMake Error at /home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rcpputils/2.2.0-1-r0/recipe-sysroot/usr/share/rcutils/cmake/ament_cmake_export_libraries-extras.cmake:48 (message):
|   Package 'rcutils' exports the library 'rcutils' which couldn't be found
| Call Stack (most recent call first):
|   /home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rcpputils/2.2.0-1-r0/recipe-sysroot/usr/share/rcutils/cmake/rcutilsConfig.cmake:41 (include)
|   CMakeLists.txt:7 (find_package)
| 
| 
| -- Configuring incomplete, errors occurred!
| See also "/home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rcpputils/2.2.0-1-r0/build/CMakeFiles/CMakeOutput.log".
| WARNING: exit code 1 from a shell command.
| 
ERROR: Task (/home1/usrdir/mtk23610/rity_images/hardknott_ros/src/poky/../meta-ros/meta-ros2-rolling/generated-recipes/rcpputils/rcpputils_2.2.0-1.bb:do_configure) failed with exit code '1'
ERROR: rcutils-4.0.2-1-r0 do_package: QA Issue: rcutils: Files/directories were installed but not shipped in any package:
  /usr/lib/librcutils.so
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
rcutils: 1 installed and not shipped files. [installed-vs-shipped]
ERROR: rcutils-4.0.2-1-r0 do_package: Fatal QA errors found, failing task.
ERROR: Logfile of failure stored in: /home1/usrdir/mtk23610/rity_images/hardknott_ros/build/tmp/work/cortexa73-cortexa53-poky-linux/rcutils/4.0.2-1-r0/temp/log.do_package.14247
ERROR: Task (/home1/usrdir/mtk23610/rity_images/hardknott_ros/src/poky/../meta-ros/meta-ros2-rolling/generated-recipes/rcutils/rcutils_4.0.2-1.bb:do_package) failed with exit code '1'
NOTE: Tasks Summary: Attempted 1411 tasks of which 1405 didn't need to be rerun and 3 failed.

Summary: 3 tasks failed:
  /home1/usrdir/mtk23610/rity_images/hardknott_ros/src/poky/../meta-ros/meta-ros2-rolling/generated-recipes/rosidl/rosidl-runtime-c_2.5.0-1.bb:do_configure
  /home1/usrdir/mtk23610/rity_images/hardknott_ros/src/poky/../meta-ros/meta-ros2-rolling/generated-recipes/rcpputils/rcpputils_2.2.0-1.bb:do_configure
  /home1/usrdir/mtk23610/rity_images/hardknott_ros/src/poky/../meta-ros/meta-ros2-rolling/generated-recipes/rcutils/rcutils_4.0.2-1.bb:do_package
Summary: There were 4 ERROR messages shown, returning a non-zero exit code.

######################################################################################
not sure what is the reason behind this. this is exactly the same (similar error) to the one found here, with no solution as of now:
https://answers.ros.org/question/381547/meta-ros-package-rcutils-exports-the-library-rcutils-which-couldnt-be-found/

rcutils library is generated, but it cannot be found due to the installed vs shipped error. puttin FILES_${PN} = ${libdir/*} doesn't seem to work to and i get the same error. This happens when i add meta-ros layer to any pre existing openembdeded project, following the steps mentioned here: https://github.com/ros/meta-ros/wiki/OpenEmbedded-Build-Instructions#add-meta-ros-to-an-existing-openembedded-project

I am not able to debug the same. any help would be nice

**Comment by shr-project** [comment]
The installed-vs-shipped QA issue is interesting, compare bitbake -e output in the standalone build and then with your pre-existing project and compare FILES:${PN} value in both and rcutils's ${WORKDIR}/packages-split directories in both of these builds.

I've recently did build with poky as well and haven't seen this, so there is probably something else being set by the pre-exiting project which affects this.

**Comment by suyash-narain** [comment]
Hi,
i started over with the prokev

> The installed-vs-shipped QA issue is interesting, compare bitbake -e output in the standalone build and then with your pre-existing project and compare FILES:${PN} value in both and rcutils's ${WORKDIR}/packages-split directories in both of these builds.
> 
> I've recently did build with poky as well and haven't seen this, so there is probably something else being set by the pre-exiting project which affects this.
