### ISSUE TITLE
do_rootfs: No manifest generated from: cyclonedds meta-ros/meta-ros2-foxy/generated-recipes/cyclonedds/cyclonedds_0.6.0-1.bb

### ISSUE THREAD

**Issue by yiyibst** [ros/meta-ros#952]
I am working on warrior branch, I develop a embedded system and provide the customers a toolchain for this target. The toolchain is generated by the populate_sdk task， The customers' apps depend on ros2-foxy, so I need to add the cyclonedds into toolchain.
When I added some components of ros2, the compiler reported an error.

Initialising tasks: 100% |###################################################################################################################################################################| Time: 0:00:04
Sstate summary: Wanted 130 Found 127 Missed 3 Current 2261 (97% match, 99% complete)
NOTE: Executing Tasks
NOTE: Setscene tasks completed
WARNING: python should use 4 spaces indentation, but found tabs in core-image-bstos.inc, line 71
WARNING: python should use 4 spaces indentation, but found tabs in core-image-bstos.inc, line 152
WARNING: python should use 4 spaces indentation, but found tabs in core-image-bstos.inc, line 177
WARNING: python should use 4 spaces indentation, but found tabs in core-image-bstos.inc, line 178
WARNING: core-image-bstos-sdk-1.0-r0 do_rootfs: Manifest /bstos-linux/bstos/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-cyclonedds.package_write_ipk not found in a1000 aarch64 allarch x86_64_x86_64-nativesdk (variant '')?
ERROR: core-image-bstos-sdk-1.0-r0 do_rootfs: No manifest generated from: cyclonedds in /home/xiyan.dong/dxy/bstos-linux/bstos/meta-ros/meta-ros2-foxy/generated-recipes/cyclonedds/cyclonedds_0.6.0-1.bb
ERROR: core-image-bstos-sdk-1.0-r0 do_rootfs: 
ERROR: core-image-bstos-sdk-1.0-r0 do_rootfs: Function failed: do_rootfs
ERROR: Logfile of failure stored in: /bstos-linux/bstos/build/tmp/work/a1000-bst-linux/core-image-bstos-sdk/1.0-r0/temp/log.do_rootfs.33712
ERROR: Task (/bstos-linux/bstos/meta-bstos/recipes-core/images/core-image-bstos-sdk.bb:do_rootfs) failed with exit code '1'

Any suggestion is appreciated, thanks

**Comment by shr-project** [comment]
warrior is EOL for over a year already, see https://wiki.yoctoproject.org/wiki/Releases

meta-ros warrior branch is also unsupported, you'll need to debug this on your own unless someone else from community responds to this ticket

**Comment by yiyibst** [comment]
Thanks, but I still hope someone can help me

**Comment by robwoolley** [comment]
Closing as Warrior and Foxy are no longer supported.
