### ISSUE TITLE
ros2-foxy component

### ISSUE THREAD

**Issue by yiyibst** [ros/meta-ros#954]
I want to use the basic communication and compilation features of ros2-foxy, what components do I need to add? And it is better to add components that do not depend on fastrtps, but only on cyclonedds.

**Comment by amamory** [comment]
late answer, but just for documenting this answer for future references ...

This tutorial is probably not for the platform you use, but this bbappend file
https://www.hackster.io/jlamperez10/ros-2-in-kria-kv260-with-petalinux-2021-2-92ec3a#toc-3---create-a-custom-image-containing-ros-2-packages-3
contains a *minimal* working set of recipes for both fastrtps and cyclonedds. As you can imagine, the *absolute minimal* set of recipes will depend on your app requirements. But i am sure you can start w this set and testing the removal of some recipes.

**Comment by robwoolley** [comment]
This question appears to have been resolved and is over 2 years old.
