### ISSUE TITLE
about ros2 environment

### ISSUE THREAD

**Issue by yiyibst** [ros/meta-ros#956]
I inherited some components of ros2 foxy in the SDK, but I don't know how to package the ros2 environment into the SDK (such as setup. Sh seup. Bash)

**Comment by robwoolley** [comment]
Typically one would need to add the ros-environment package by adding it to TOOLCHAIN_HOST_TASK:append = "ros-environment".

See the ros2-image-sdktest image recipe for a reference example: https://github.com/ros/meta-ros/blob/master-next/meta-ros2/recipes-core/images/ros2-image-sdktest.bb
