### ISSUE TITLE
build ros2 sdk

### ISSUE THREAD

**Issue by yiyibst** [ros/meta-ros#960]
When building the sdk and adding the ros1-melodic component bb file, it generates the folder opt/ros/melodic under the sdk, which contains the ros1 environment and ros1 related stuff. But when the same ros2-foxy component bb file is added, why is there no opt/ros/foxy folder generated? If there is no opt/ros/foxy, what if I change the environment if soruce ros2-foxy?

**Comment by shr-project** [comment]
Because only ROS1 distributions are currently using ros_opt_prefix.bbclass.

**Comment by yiyibst** [comment]
but how to find the ros2 environment in the sdk, and how to source ros2 environment

**Comment by SergeyFabric** [comment]
@yiyibst  did you find a solution? I managed to build ros2 foxy recipe inside yocto but cannot use the SDK for crosscompile on another machine.

**Comment by robwoolley** [comment]
@yiybst and @SergeyFabric   We have now added support for ros_opt_prefix and SDKs.  Step-by-step instructions on how to use it to come.  Please let me know if you are interested in checking it out and I can help you get set up.
