### ISSUE TITLE
Question on how to start using meta-ros

### ISSUE THREAD

**Issue by KansaiUser** [ros/meta-ros#990]
I have read the [build instructions](https://github.com/ros/meta-ros/wiki/OpenEmbedded-Build-Instructions) and I have some questions:

1. Is 
`git clone -b build --single-branch git@github.com:ros/meta-ros build`
all that is necessary to clone? In other words, isn't it necessary to clone `git://git.yoctoproject.org/poky.git` as well previously?

2.  Is it really necessary to have 100GB of free space? Is it really this big?
3. I don't understand step 2 "Add meta-ros[12]-<ROS_DISTRO> to your conf/bblayers.conf." of "Add meta-ros to an Existing OpenEmbedded Project "  What does the "12" stand for? This is a separate instructions to add meta-ros right? The previous one is to build a new one from scratch?
Thanks for the help

**Comment by jlamperez** [comment]
Hi @KansaiUser 

When you do `git clone -b build --single-branch git@github.com:ros/meta-ros build` you are cloning the `meta-ros` `build` branch and you save these files into a `build` folder. In this branch you have something like this:

![meta-ros-build](https://user-images.githubusercontent.com/8319840/151668621-e1f6cc1a-ed3c-4ad8-a53b-1ced8ebe8232.png)

These are files and scripts for building bitbake environment.

If you follow the build instructions in this folder then you need to make a `conf` folder and make a symbolic link to it that will appear at the `build` level.

```
mkdir conf
ln -snf ../conf build/.
```

Then you need to choose which is the `.mcf` you want from the `build/scripts/mcf` folder. To that end, you need to choose a `distro`, `ros_distro`, and `oe_release_series`.

For example, if you want ros2, galactic and for yocto release gatesgarth you need to type in the console:

```
distro=ros2
ros_distro=galactic
oe_release_series=gatesgarth
```

Then if you type:

```
cfg=$distro-$ros_distro-$oe_release_series.mcf
```

You will be choosing the `ros2-galactic-gatesgarth.mcf` configuration file.

With the command `cp build/files/$cfg conf/.` you are copying the [ros2-galactic-gatesgarth.mcf](https://github.com/ros/meta-ros/blob/build/files/ros2-galactic-gatesgarth.mcf) to the conf folder.

This configuration file contains the layer versions that will be downloaded, for example:

```
MetaRos_RepoURL = getenv('MCF_META_ROS_REPO_URL', 'https://github.com/ros/meta-ros.git')
MetaRos_Branch  = getenv('MCF_META_ROS_BRANCH',   OE_Branch)
MetaRos_Commit  = getenv('MCF_META_ROS_COMMIT',   '4e66ddf2f')
```

```
Layers = [
('bitbake',                            -1, 'https://github.com/openembedded/bitbake.git',            {'branch': Bitbake_Branch,       'commit': '92bb53ad'},          {}),

('meta',                                5, 'https://github.com/openembedded/openembedded-core.git',  {'branch': OE_Branch,            'commit': '9cce475ffc'},        {}),

('meta-oe',                            10, 'https://github.com/openembedded/meta-openembedded.git',  {'branch': OE_Branch,            'commit': 'f3f7a5f1a4'},        {}),
('meta-python',                        13, 'https://github.com/openembedded/meta-openembedded.git',  {},                                                              {}),

('meta-ros-backports-hardknott',       36, MetaRos_RepoURL,                                          {},                                                              {}),
('meta-ros-common',                    37, MetaRos_RepoURL,                                          {'branch': MetaRos_Branch,       'commit': MetaRos_Commit},      {}),
('meta-ros2',                          38, MetaRos_RepoURL,                                          {},                                                              {}),
('meta-ros2-' + ROS_Distribution,      39, MetaRos_RepoURL,                                          {},                                                              {}),

('meta-raspberrypi',                   50, 'https://github.com/agherzan/meta-raspberrypi.git',       {'branch': OE_Branch,            'commit': 'e5e976d'},           {}),
]
```

Then as commented in the instructions with `build/scripts/mcf -f conf/$cfg` you are cloning all OpenEmbedded metadata layers and generating a `conf/bblayers.conf` file.

At the end you will have something like this:

```
artifacts  bitbake  build  conf  meta-openembedded  meta-raspberrypi  meta-ros  openembedded-core
```

This is how looks like a Yocto project. If then you do `source openembedded-core/oe-init-build-env` you are sourcing Yocto environment.

You need to add also the pointed configurations in `conf/local.conf ` as pointed in step3 and change the `ROS_COMMON_ARTIFACTS ?= "<ABSOLUTE-PATH-TO-DIRECTORY-ON-SEPARATE-DISK>"` to the folder you have created in 2.

Now if you go to the root you can create an image with `bitbake ros-image-core`.

The [Add meta-ros to an Existing OpenEmbedded Project](https://github.com/ros/meta-ros/wiki/OpenEmbedded-Build-Instructions#add-meta-ros-to-an-existing-openembedded-project) is only if you want to add `meta-ros` for a Yocto project that has been previously created.
