### ISSUE TITLE
Is it possible to build both ros1 melodic and ros2 foxy into the same image?

### ISSUE THREAD

**Issue by yiyibst** [ros/meta-ros#994]
Is it possible to build both ros1 melodic and ros2 foxy into the same image?

**Comment by herb-kuta-lge** [comment]
Currently it's not possible, but we had plans to allow it: https://github.com/ros/meta-ros/wiki/Superflore-OE-Recipe-Generation-Scheme/f2123c4043a6b13f9efc4312991144c5e5e4963d#defer-until-ros_superflore_generation_scheme-3 .
