### ISSUE TITLE
Error: No Python binding generator found

### ISSUE THREAD

**Issue by ABTrac** [ros/meta-ros#998]
Dear ROS community,

I am running into a problem when want to add `meta-ros` to an existing yocto build for `Nvidia Jetson-agx-xavier`. I have added `meta-ros `as instructed in [https://github.com/ros/meta-ros/wiki/OpenEmbedded-Build-Instructions#add-meta-ros-to-an-existing-openembedded-project](https://github.com/ros/meta-ros/issues/url) and everything was successfully compiled including the `ros-image-core`. However, when I wanted to add `rviz` to the image I got the following configuration errors:
![Screenshot from 2022-04-14 11-33-53](https://user-images.githubusercontent.com/82082166/164248065-04587b99-3fbe-42d6-8dd8-a63c274144e9.png)

I am building the image from the Dunfell branch, and I have added `meta-qt5` layer and also added `sip` in `local.conf` `IMAGE_INSTALL_append= " sip"` and removed `rviz` from the blacklist. 

Any idea how to fix the `No Python binding generator found` error? I have tried to help cmake by setting `CMAKE_PREFIX_PATH` and 
`Qt5_DIR` at the begging of the `sip_helper.cmake` as follows:

`set(CMAKE_PREFIX_PATH "/media/tracoven/Storage/Nvidia/jetpack-4.6/build/tmp/sysroots-components/aarch64/qtbase/usr/lib/cmake/Qt5/")`

`set(Qt5_DIR "/media/tracoven/Storage/Nvidia/jetpack-4.6/build/tmp/sysroots-components/aarch64/qtbase/usr/lib/cmake/Qt5/" CACHE PATH "directory where Qt5Config.cmake exists.")`

but unfortunately I still get the same error. Any suggestions will be really appreciated.  Thank you.

**Comment by robwoolley** [comment]
The Python bindings were pushed upstream.  To follow the work to integrate rviz can be found here: https://github.com/ros/meta-ros/pull/1144

Closing this for now, but please feel free to reopen if you still have this problem.
